; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=thumbv6m-eabi -frame-pointer=none %s -o - --verify-machineinstrs | FileCheck %s --check-prefixes=CHECK,CHECK-NOFP,CHECK-ATPCS
; RUN: llc -mtriple=thumbv6m-eabi -frame-pointer=all %s -o - --verify-machineinstrs | FileCheck %s --check-prefixes=CHECK,CHECK-FP-ATPCS,CHECK-ATPCS
; RUN: llc -mtriple=thumbv6m-eabi -frame-pointer=none -mattr=+aapcs-frame-chain %s -o - --verify-machineinstrs | FileCheck %s --check-prefixes=CHECK,CHECK-NOFP,CHECK-AAPCS
; RUN: llc -mtriple=thumbv6m-eabi -frame-pointer=all -mattr=+aapcs-frame-chain %s -o - --verify-machineinstrs | FileCheck %s --check-prefixes=CHECK,CHECK-FP-AAPCS,CHECK-AAPCS

; struct S { int x[128]; } s;
; int f(int *, int, int, int, struct S);
; int g(int *, int, int, int, int, int);
; int h(int *, int *, int *);
; int u(int *, int *, int *, struct S, struct S);

%struct.S = type { [128 x i32] }
%struct.__va_list = type { ptr }

@s = common dso_local global %struct.S zeroinitializer, align 4

declare void @llvm.va_start(ptr)
declare dso_local i32 @i(i32) local_unnamed_addr
declare dso_local i32 @g(ptr, i32, i32, i32, i32, i32) local_unnamed_addr
declare dso_local i32 @f(ptr, i32, i32, i32, ptr byval(%struct.S) align 4) local_unnamed_addr
declare dso_local i32 @h(ptr, ptr, ptr) local_unnamed_addr
declare dso_local i32 @u(ptr, ptr, ptr, ptr byval(%struct.S) align 4, ptr byval(%struct.S) align 4) local_unnamed_addr

;
; Test access to arguments, passed on stack (including varargs)
;

; Usual case, access via SP if FP is not available
; int test_args_sp(int a, int b, int c, int d, int e) {
;   int v[4];
;   return g(v, a, b, c, d, e);
; }
define dso_local i32 @test_args_sp(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e) local_unnamed_addr {
; CHECK-NOFP-LABEL: test_args_sp:
; CHECK-NOFP:       @ %bb.0: @ %entry
; CHECK-NOFP-NEXT:    .save {r4, lr}
; CHECK-NOFP-NEXT:    push {r4, lr}
; CHECK-NOFP-NEXT:    .pad #24
; CHECK-NOFP-NEXT:    sub sp, #24
; CHECK-NOFP-NEXT:    str r3, [sp]
; CHECK-NOFP-NEXT:    mov r4, r2
; CHECK-NOFP-NEXT:    mov r2, r1
; CHECK-NOFP-NEXT:    mov r1, r0
; CHECK-NOFP-NEXT:    ldr r0, [sp, #32]
; CHECK-NOFP-NEXT:    str r0, [sp, #4]
; CHECK-NOFP-NEXT:    add r0, sp, #8
; CHECK-NOFP-NEXT:    mov r3, r4
; CHECK-NOFP-NEXT:    bl g
; CHECK-NOFP-NEXT:    add sp, #24
; CHECK-NOFP-NEXT:    pop {r4, pc}
;
; CHECK-FP-ATPCS-LABEL: test_args_sp:
; CHECK-FP-ATPCS:       @ %bb.0: @ %entry
; CHECK-FP-ATPCS-NEXT:    .save {r4, r6, r7, lr}
; CHECK-FP-ATPCS-NEXT:    push {r4, r6, r7, lr}
; CHECK-FP-ATPCS-NEXT:    .setfp r7, sp, #8
; CHECK-FP-ATPCS-NEXT:    add r7, sp, #8
; CHECK-FP-ATPCS-NEXT:    .pad #24
; CHECK-FP-ATPCS-NEXT:    sub sp, #24
; CHECK-FP-ATPCS-NEXT:    str r3, [sp]
; CHECK-FP-ATPCS-NEXT:    mov r4, r2
; CHECK-FP-ATPCS-NEXT:    mov r2, r1
; CHECK-FP-ATPCS-NEXT:    mov r1, r0
; CHECK-FP-ATPCS-NEXT:    ldr r0, [r7, #8]
; CHECK-FP-ATPCS-NEXT:    str r0, [sp, #4]
; CHECK-FP-ATPCS-NEXT:    add r0, sp, #8
; CHECK-FP-ATPCS-NEXT:    mov r3, r4
; CHECK-FP-ATPCS-NEXT:    bl g
; CHECK-FP-ATPCS-NEXT:    add sp, #24
; CHECK-FP-ATPCS-NEXT:    pop {r4, r6, r7, pc}
;
; CHECK-FP-AAPCS-LABEL: test_args_sp:
; CHECK-FP-AAPCS:       @ %bb.0: @ %entry
; CHECK-FP-AAPCS-NEXT:    .save {lr}
; CHECK-FP-AAPCS-NEXT:    push {lr}
; CHECK-FP-AAPCS-NEXT:    mov lr, r11
; CHECK-FP-AAPCS-NEXT:    .save {r11}
; CHECK-FP-AAPCS-NEXT:    push {lr}
; CHECK-FP-AAPCS-NEXT:    .setfp r11, sp
; CHECK-FP-AAPCS-NEXT:    mov r11, sp
; CHECK-FP-AAPCS-NEXT:    .save {r4, r7}
; CHECK-FP-AAPCS-NEXT:    push {r4, r7}
; CHECK-FP-AAPCS-NEXT:    .pad #24
; CHECK-FP-AAPCS-NEXT:    sub sp, #24
; CHECK-FP-AAPCS-NEXT:    str r3, [sp]
; CHECK-FP-AAPCS-NEXT:    mov r4, r2
; CHECK-FP-AAPCS-NEXT:    mov r2, r1
; CHECK-FP-AAPCS-NEXT:    mov r1, r0
; CHECK-FP-AAPCS-NEXT:    mov r0, r11
; CHECK-FP-AAPCS-NEXT:    ldr r0, [r0, #8]
; CHECK-FP-AAPCS-NEXT:    str r0, [sp, #4]
; CHECK-FP-AAPCS-NEXT:    add r0, sp, #8
; CHECK-FP-AAPCS-NEXT:    mov r3, r4
; CHECK-FP-AAPCS-NEXT:    bl g
; CHECK-FP-AAPCS-NEXT:    add sp, #24
; CHECK-FP-AAPCS-NEXT:    pop {r4, r7}
; CHECK-FP-AAPCS-NEXT:    pop {r1}
; CHECK-FP-AAPCS-NEXT:    mov r11, r1
; CHECK-FP-AAPCS-NEXT:    pop {pc}
entry:
  %v = alloca [4 x i32], align 4
  %call = call i32 @g(ptr nonnull %v, i32 %a, i32 %b, i32 %c, i32 %d, i32 %e)
  ret i32 %call
}
; CHECK-LABEL: test_args_sp
; Load `e`
; CHECK-NOFP: ldr    r0, [sp, #32]
; CHECK-FP-ATPCS: ldr  r0, [r7, #8]
; CHECK-FP-AAPCS: mov    r0, r11
; CHECK-FP-AAPCS: ldr    r0, [r0, #8]
; CHECK-NEXT:  str    r3, [sp]
; Pass `e` on stack
; CHECK-NEXT:  str    r0, [sp, #4]
; CHECK:       bl    g

; int test_varargs_sp(int a, ...) {
;   int v[4];
;   __builtin_va_list ap;
;   __builtin_va_start(ap, a);
;   return g(v, a, 0, 0, 0, 0);
; }
define dso_local i32 @test_varargs_sp(i32 %a, ...) local_unnamed_addr  {
; CHECK-NOFP-LABEL: test_varargs_sp:
; CHECK-NOFP:       @ %bb.0: @ %entry
; CHECK-NOFP-NEXT:    .pad #12
; CHECK-NOFP-NEXT:    sub sp, #12
; CHECK-NOFP-NEXT:    .save {r4, lr}
; CHECK-NOFP-NEXT:    push {r4, lr}
; CHECK-NOFP-NEXT:    .pad #28
; CHECK-NOFP-NEXT:    sub sp, #28
; CHECK-NOFP-NEXT:    str r1, [sp, #36]
; CHECK-NOFP-NEXT:    mov r4, r0
; CHECK-NOFP-NEXT:    str r2, [sp, #40]
; CHECK-NOFP-NEXT:    str r3, [sp, #44]
; CHECK-NOFP-NEXT:    add r0, sp, #36
; CHECK-NOFP-NEXT:    str r0, [sp, #8]
; CHECK-NOFP-NEXT:    movs r2, #0
; CHECK-NOFP-NEXT:    str r2, [sp]
; CHECK-NOFP-NEXT:    str r2, [sp, #4]
; CHECK-NOFP-NEXT:    add r0, sp, #12
; CHECK-NOFP-NEXT:    mov r1, r4
; CHECK-NOFP-NEXT:    mov r3, r2
; CHECK-NOFP-NEXT:    bl g
; CHECK-NOFP-NEXT:    add sp, #28
; CHECK-NOFP-NEXT:    pop {r4}
; CHECK-NOFP-NEXT:    pop {r1}
; CHECK-NOFP-NEXT:    add sp, #12
; CHECK-NOFP-NEXT:    bx r1
;
; CHECK-FP-ATPCS-LABEL: test_varargs_sp:
; CHECK-FP-ATPCS:       @ %bb.0: @ %entry
; CHECK-FP-ATPCS-NEXT:    .pad #12
; CHECK-FP-ATPCS-NEXT:    sub sp, #12
; CHECK-FP-ATPCS-NEXT:    .save {r4, r6, r7, lr}
; CHECK-FP-ATPCS-NEXT:    push {r4, r6, r7, lr}
; CHECK-FP-ATPCS-NEXT:    .setfp r7, sp, #8
; CHECK-FP-ATPCS-NEXT:    add r7, sp, #8
; CHECK-FP-ATPCS-NEXT:    .pad #28
; CHECK-FP-ATPCS-NEXT:    sub sp, #28
; CHECK-FP-ATPCS-NEXT:    str r1, [r7, #8]
; CHECK-FP-ATPCS-NEXT:    mov r4, r0
; CHECK-FP-ATPCS-NEXT:    str r2, [r7, #12]
; CHECK-FP-ATPCS-NEXT:    str r3, [r7, #16]
; CHECK-FP-ATPCS-NEXT:    adds r0, r7, #7
; CHECK-FP-ATPCS-NEXT:    adds r0, #1
; CHECK-FP-ATPCS-NEXT:    str r0, [sp, #8]
; CHECK-FP-ATPCS-NEXT:    movs r2, #0
; CHECK-FP-ATPCS-NEXT:    str r2, [sp]
; CHECK-FP-ATPCS-NEXT:    str r2, [sp, #4]
; CHECK-FP-ATPCS-NEXT:    add r0, sp, #12
; CHECK-FP-ATPCS-NEXT:    mov r1, r4
; CHECK-FP-ATPCS-NEXT:    mov r3, r2
; CHECK-FP-ATPCS-NEXT:    bl g
; CHECK-FP-ATPCS-NEXT:    add sp, #28
; CHECK-FP-ATPCS-NEXT:    pop {r4, r6, r7}
; CHECK-FP-ATPCS-NEXT:    pop {r1}
; CHECK-FP-ATPCS-NEXT:    add sp, #12
; CHECK-FP-ATPCS-NEXT:    bx r1
;
; CHECK-FP-AAPCS-LABEL: test_varargs_sp:
; CHECK-FP-AAPCS:       @ %bb.0: @ %entry
; CHECK-FP-AAPCS-NEXT:    .pad #12
; CHECK-FP-AAPCS-NEXT:    sub sp, #12
; CHECK-FP-AAPCS-NEXT:    .save {lr}
; CHECK-FP-AAPCS-NEXT:    push {lr}
; CHECK-FP-AAPCS-NEXT:    mov lr, r11
; CHECK-FP-AAPCS-NEXT:    .save {r11}
; CHECK-FP-AAPCS-NEXT:    push {lr}
; CHECK-FP-AAPCS-NEXT:    .setfp r11, sp
; CHECK-FP-AAPCS-NEXT:    mov r11, sp
; CHECK-FP-AAPCS-NEXT:    .save {r4, r7}
; CHECK-FP-AAPCS-NEXT:    push {r4, r7}
; CHECK-FP-AAPCS-NEXT:    .pad #28
; CHECK-FP-AAPCS-NEXT:    sub sp, #28
; CHECK-FP-AAPCS-NEXT:    mov r4, r11
; CHECK-FP-AAPCS-NEXT:    str r1, [r4, #8]
; CHECK-FP-AAPCS-NEXT:    mov r4, r0
; CHECK-FP-AAPCS-NEXT:    mov r0, r11
; CHECK-FP-AAPCS-NEXT:    str r2, [r0, #12]
; CHECK-FP-AAPCS-NEXT:    str r3, [r0, #16]
; CHECK-FP-AAPCS-NEXT:    adds r0, #8
; CHECK-FP-AAPCS-NEXT:    str r0, [sp, #8]
; CHECK-FP-AAPCS-NEXT:    movs r2, #0
; CHECK-FP-AAPCS-NEXT:    str r2, [sp]
; CHECK-FP-AAPCS-NEXT:    str r2, [sp, #4]
; CHECK-FP-AAPCS-NEXT:    add r0, sp, #12
; CHECK-FP-AAPCS-NEXT:    mov r1, r4
; CHECK-FP-AAPCS-NEXT:    mov r3, r2
; CHECK-FP-AAPCS-NEXT:    bl g
; CHECK-FP-AAPCS-NEXT:    add sp, #28
; CHECK-FP-AAPCS-NEXT:    pop {r4, r7}
; CHECK-FP-AAPCS-NEXT:    pop {r1}
; CHECK-FP-AAPCS-NEXT:    mov r11, r1
; CHECK-FP-AAPCS-NEXT:    pop {r1}
; CHECK-FP-AAPCS-NEXT:    add sp, #12
; CHECK-FP-AAPCS-NEXT:    bx r1
entry:
  %v = alloca [4 x i32], align 4
  %ap = alloca %struct.__va_list, align 4
  call void @llvm.va_start(ptr nonnull %ap)
  %call = call i32 @g(ptr nonnull %v, i32 %a, i32 0, i32 0, i32 0, i32 0)
  ret i32 %call
}
; CHECK-LABEL: test_varargs_sp
; Three incoming varargs in registers
; CHECK:       sub sp, #12
; CHECK:       sub sp, #28
; Incoming arguments area is accessed via SP if FP is not available
; CHECK-NOFP:  add r0, sp, #36
; CHECK-NOFP:  stm r0!, {r1, r2, r3}
; CHECK-FP-ATPCS: mov r0, r7
; CHECK-FP-ATPCS: adds r0, #8
; CHECK-FP-ATPCS: stm r0!, {r1, r2, r3}
; CHECK-FP-AAPCS: mov r0, r11
; CHECK-FP-AAPCS: mov r7, r0
; CHECK-FP-AAPCS: adds r7, #8
; CHECK-FP-AAPCS: stm r7!, {r1, r2, r3}
; Re-aligned stack, access via FP
; int test_args_realign(int a, int b, int c, int d, int e) {
;   __attribute__((aligned(16))) int v[4];
;   return g(v, a, b, c, d, e);
; }
; Function Attrs: nounwind
define dso_local i32 @test_args_realign(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e) local_unnamed_addr  {
; CHECK-ATPCS-LABEL: test_args_realign:
; CHECK-ATPCS:       @ %bb.0: @ %entry
; CHECK-ATPCS-NEXT:    .save {r4, r6, r7, lr}
; CHECK-ATPCS-NEXT:    push {r4, r6, r7, lr}
; CHECK-ATPCS-NEXT:    .setfp r7, sp, #8
; CHECK-ATPCS-NEXT:    add r7, sp, #8
; CHECK-ATPCS-NEXT:    .pad #32
; CHECK-ATPCS-NEXT:    sub sp, #32
; CHECK-ATPCS-NEXT:    mov r4, sp
; CHECK-ATPCS-NEXT:    lsrs r4, r4, #4
; CHECK-ATPCS-NEXT:    lsls r4, r4, #4
; CHECK-ATPCS-NEXT:    mov sp, r4
; CHECK-ATPCS-NEXT:    str r3, [sp]
; CHECK-ATPCS-NEXT:    mov r4, r2
; CHECK-ATPCS-NEXT:    mov r2, r1
; CHECK-ATPCS-NEXT:    mov r1, r0
; CHECK-ATPCS-NEXT:    ldr r0, [r7, #8]
; CHECK-ATPCS-NEXT:    str r0, [sp, #4]
; CHECK-ATPCS-NEXT:    add r0, sp, #16
; CHECK-ATPCS-NEXT:    mov r3, r4
; CHECK-ATPCS-NEXT:    bl g
; CHECK-ATPCS-NEXT:    subs r6, r7, #7
; CHECK-ATPCS-NEXT:    subs r6, #1
; CHECK-ATPCS-NEXT:    mov sp, r6
; CHECK-ATPCS-NEXT:    pop {r4, r6, r7, pc}
;
; CHECK-FP-ATPCS-LABEL: test_args_realign:
; CHECK-FP-ATPCS:       @ %bb.0: @ %entry
; CHECK-FP-ATPCS-NEXT:    .save {r4, r6, r7, lr}
; CHECK-FP-ATPCS-NEXT:    push {r4, r6, r7, lr}
; CHECK-FP-ATPCS-NEXT:    .setfp r7, sp, #8
; CHECK-FP-ATPCS-NEXT:    add r7, sp, #8
; CHECK-FP-ATPCS-NEXT:    .pad #32
; CHECK-FP-ATPCS-NEXT:    sub sp, #32
; CHECK-FP-ATPCS-NEXT:    mov r4, sp
; CHECK-FP-ATPCS-NEXT:    lsrs r4, r4, #4
; CHECK-FP-ATPCS-NEXT:    lsls r4, r4, #4
; CHECK-FP-ATPCS-NEXT:    mov sp, r4
; CHECK-FP-ATPCS-NEXT:    str r3, [sp]
; CHECK-FP-ATPCS-NEXT:    mov r4, r2
; CHECK-FP-ATPCS-NEXT:    mov r2, r1
; CHECK-FP-ATPCS-NEXT:    mov r1, r0
; CHECK-FP-ATPCS-NEXT:    ldr r0, [r7, #8]
; CHECK-FP-ATPCS-NEXT:    str r0, [sp, #4]
; CHECK-FP-ATPCS-NEXT:    add r0, sp, #16
; CHECK-FP-ATPCS-NEXT:    mov r3, r4
; CHECK-FP-ATPCS-NEXT:    bl g
; CHECK-FP-ATPCS-NEXT:    subs r6, r7, #7
; CHECK-FP-ATPCS-NEXT:    subs r6, #1
; CHECK-FP-ATPCS-NEXT:    mov sp, r6
; CHECK-FP-ATPCS-NEXT:    pop {r4, r6, r7, pc}
;
; CHECK-AAPCS-LABEL: test_args_realign:
; CHECK-AAPCS:       @ %bb.0: @ %entry
; CHECK-AAPCS-NEXT:    .save {lr}
; CHECK-AAPCS-NEXT:    push {lr}
; CHECK-AAPCS-NEXT:    mov lr, r11
; CHECK-AAPCS-NEXT:    .save {r11}
; CHECK-AAPCS-NEXT:    push {lr}
; CHECK-AAPCS-NEXT:    .setfp r11, sp
; CHECK-AAPCS-NEXT:    mov r11, sp
; CHECK-AAPCS-NEXT:    .save {r4, r7}
; CHECK-AAPCS-NEXT:    push {r4, r7}
; CHECK-AAPCS-NEXT:    .pad #32
; CHECK-AAPCS-NEXT:    sub sp, #32
; CHECK-AAPCS-NEXT:    mov r4, sp
; CHECK-AAPCS-NEXT:    lsrs r4, r4, #4
; CHECK-AAPCS-NEXT:    lsls r4, r4, #4
; CHECK-AAPCS-NEXT:    mov sp, r4
; CHECK-AAPCS-NEXT:    str r3, [sp]
; CHECK-AAPCS-NEXT:    mov r4, r2
; CHECK-AAPCS-NEXT:    mov r2, r1
; CHECK-AAPCS-NEXT:    mov r1, r0
; CHECK-AAPCS-NEXT:    mov r0, r11
; CHECK-AAPCS-NEXT:    ldr r0, [r0, #8]
; CHECK-AAPCS-NEXT:    str r0, [sp, #4]
; CHECK-AAPCS-NEXT:    add r0, sp, #16
; CHECK-AAPCS-NEXT:    mov r3, r4
; CHECK-AAPCS-NEXT:    bl g
; CHECK-AAPCS-NEXT:    mov r7, r11
; CHECK-AAPCS-NEXT:    subs r7, #8
; CHECK-AAPCS-NEXT:    mov sp, r7
; CHECK-AAPCS-NEXT:    pop {r4, r7}
; CHECK-AAPCS-NEXT:    pop {r1}
; CHECK-AAPCS-NEXT:    mov r11, r1
; CHECK-AAPCS-NEXT:    pop {pc}
;
; CHECK-FP-AAPCS-LABEL: test_args_realign:
; CHECK-FP-AAPCS:       @ %bb.0: @ %entry
; CHECK-FP-AAPCS-NEXT:    .save {lr}
; CHECK-FP-AAPCS-NEXT:    push {lr}
; CHECK-FP-AAPCS-NEXT:    mov lr, r11
; CHECK-FP-AAPCS-NEXT:    .save {r11}
; CHECK-FP-AAPCS-NEXT:    push {lr}
; CHECK-FP-AAPCS-NEXT:    .setfp r11, sp
; CHECK-FP-AAPCS-NEXT:    mov r11, sp
; CHECK-FP-AAPCS-NEXT:    .save {r4, r7}
; CHECK-FP-AAPCS-NEXT:    push {r4, r7}
; CHECK-FP-AAPCS-NEXT:    .pad #32
; CHECK-FP-AAPCS-NEXT:    sub sp, #32
; CHECK-FP-AAPCS-NEXT:    mov r4, sp
; CHECK-FP-AAPCS-NEXT:    lsrs r4, r4, #4
; CHECK-FP-AAPCS-NEXT:    lsls r4, r4, #4
; CHECK-FP-AAPCS-NEXT:    mov sp, r4
; CHECK-FP-AAPCS-NEXT:    str r3, [sp]
; CHECK-FP-AAPCS-NEXT:    mov r4, r2
; CHECK-FP-AAPCS-NEXT:    mov r2, r1
; CHECK-FP-AAPCS-NEXT:    mov r1, r0
; CHECK-FP-AAPCS-NEXT:    mov r0, r11
; CHECK-FP-AAPCS-NEXT:    ldr r0, [r0, #8]
; CHECK-FP-AAPCS-NEXT:    str r0, [sp, #4]
; CHECK-FP-AAPCS-NEXT:    add r0, sp, #16
; CHECK-FP-AAPCS-NEXT:    mov r3, r4
; CHECK-FP-AAPCS-NEXT:    bl g
; CHECK-FP-AAPCS-NEXT:    mov r7, r11
; CHECK-FP-AAPCS-NEXT:    subs r7, #8
; CHECK-FP-AAPCS-NEXT:    mov sp, r7
; CHECK-FP-AAPCS-NEXT:    pop {r4, r7}
; CHECK-FP-AAPCS-NEXT:    pop {r1}
; CHECK-FP-AAPCS-NEXT:    mov r11, r1
; CHECK-FP-AAPCS-NEXT:    pop {pc}
entry:
  %v = alloca [4 x i32], align 16
  %call = call i32 @g(ptr nonnull %v, i32 %a, i32 %b, i32 %c, i32 %d, i32 %e)
  ret i32 %call
}
; CHECK-LABEL: test_args_realign
; Setup frame pointer
; CHECK-ATPCS: add r7, sp, #8
; CHECK-AAPCS: mov r11, sp
; Align stack
; CHECK:       mov  r4, sp
; CHECK-NEXT:  lsrs r4, r4, #4
; CHECK-NEXT:  lsls r4, r4, #4
; CHECK-NEXT:  mov  sp, r4
; Load `e` via FP
; CHECK-ATPCS: ldr r0, [r7, #8]
; CHECK-AAPCS: mov r0, r11
; CHECK-AAPCS: ldr r0, [r0, #8]
; CHECK-NEXT:  str r3, [sp]
; Pass `e` as argument
; CHECK-NEXT:  str r0, [sp, #4]
; CHECK:       bl    g

; int test_varargs_realign(int a, ...) {
;   __attribute__((aligned(16))) int v[4];
;   __builtin_va_list ap;
;   __builtin_va_start(ap, a);
;   return g(v, a, 0, 0, 0, 0);
; }
define dso_local i32 @test_varargs_realign(i32 %a, ...) local_unnamed_addr  {
; CHECK-ATPCS-LABEL: test_varargs_realign:
; CHECK-ATPCS:       @ %bb.0: @ %entry
; CHECK-ATPCS-NEXT:    .pad #12
; CHECK-ATPCS-NEXT:    sub sp, #12
; CHECK-ATPCS-NEXT:    .save {r4, r6, r7, lr}
; CHECK-ATPCS-NEXT:    push {r4, r6, r7, lr}
; CHECK-ATPCS-NEXT:    .setfp r7, sp, #8
; CHECK-ATPCS-NEXT:    add r7, sp, #8
; CHECK-ATPCS-NEXT:    .pad #36
; CHECK-ATPCS-NEXT:    sub sp, #36
; CHECK-ATPCS-NEXT:    mov r4, sp
; CHECK-ATPCS-NEXT:    lsrs r4, r4, #4
; CHECK-ATPCS-NEXT:    lsls r4, r4, #4
; CHECK-ATPCS-NEXT:    mov sp, r4
; CHECK-ATPCS-NEXT:    str r1, [r7, #8]
; CHECK-ATPCS-NEXT:    mov r4, r0
; CHECK-ATPCS-NEXT:    str r2, [r7, #12]
; CHECK-ATPCS-NEXT:    str r3, [r7, #16]
; CHECK-ATPCS-NEXT:    adds r0, r7, #7
; CHECK-ATPCS-NEXT:    adds r0, #1
; CHECK-ATPCS-NEXT:    str r0, [sp, #12]
; CHECK-ATPCS-NEXT:    movs r2, #0
; CHECK-ATPCS-NEXT:    str r2, [sp]
; CHECK-ATPCS-NEXT:    str r2, [sp, #4]
; CHECK-ATPCS-NEXT:    add r0, sp, #16
; CHECK-ATPCS-NEXT:    mov r1, r4
; CHECK-ATPCS-NEXT:    mov r3, r2
; CHECK-ATPCS-NEXT:    bl g
; CHECK-ATPCS-NEXT:    subs r6, r7, #7
; CHECK-ATPCS-NEXT:    subs r6, #1
; CHECK-ATPCS-NEXT:    mov sp, r6
; CHECK-ATPCS-NEXT:    pop {r4, r6, r7}
; CHECK-ATPCS-NEXT:    pop {r1}
; CHECK-ATPCS-NEXT:    add sp, #12
; CHECK-ATPCS-NEXT:    bx r1
;
; CHECK-FP-ATPCS-LABEL: test_varargs_realign:
; CHECK-FP-ATPCS:       @ %bb.0: @ %entry
; CHECK-FP-ATPCS-NEXT:    .pad #12
; CHECK-FP-ATPCS-NEXT:    sub sp, #12
; CHECK-FP-ATPCS-NEXT:    .save {r4, r6, r7, lr}
; CHECK-FP-ATPCS-NEXT:    push {r4, r6, r7, lr}
; CHECK-FP-ATPCS-NEXT:    .setfp r7, sp, #8
; CHECK-FP-ATPCS-NEXT:    add r7, sp, #8
; CHECK-FP-ATPCS-NEXT:    .pad #36
; CHECK-FP-ATPCS-NEXT:    sub sp, #36
; CHECK-FP-ATPCS-NEXT:    mov r4, sp
; CHECK-FP-ATPCS-NEXT:    lsrs r4, r4, #4
; CHECK-FP-ATPCS-NEXT:    lsls r4, r4, #4
; CHECK-FP-ATPCS-NEXT:    mov sp, r4
; CHECK-FP-ATPCS-NEXT:    str r1, [r7, #8]
; CHECK-FP-ATPCS-NEXT:    mov r4, r0
; CHECK-FP-ATPCS-NEXT:    str r2, [r7, #12]
; CHECK-FP-ATPCS-NEXT:    str r3, [r7, #16]
; CHECK-FP-ATPCS-NEXT:    adds r0, r7, #7
; CHECK-FP-ATPCS-NEXT:    adds r0, #1
; CHECK-FP-ATPCS-NEXT:    str r0, [sp, #12]
; CHECK-FP-ATPCS-NEXT:    movs r2, #0
; CHECK-FP-ATPCS-NEXT:    str r2, [sp]
; CHECK-FP-ATPCS-NEXT:    str r2, [sp, #4]
; CHECK-FP-ATPCS-NEXT:    add r0, sp, #16
; CHECK-FP-ATPCS-NEXT:    mov r1, r4
; CHECK-FP-ATPCS-NEXT:    mov r3, r2
; CHECK-FP-ATPCS-NEXT:    bl g
; CHECK-FP-ATPCS-NEXT:    subs r6, r7, #7
; CHECK-FP-ATPCS-NEXT:    subs r6, #1
; CHECK-FP-ATPCS-NEXT:    mov sp, r6
; CHECK-FP-ATPCS-NEXT:    pop {r4, r6, r7}
; CHECK-FP-ATPCS-NEXT:    pop {r1}
; CHECK-FP-ATPCS-NEXT:    add sp, #12
; CHECK-FP-ATPCS-NEXT:    bx r1
;
; CHECK-AAPCS-LABEL: test_varargs_realign:
; CHECK-AAPCS:       @ %bb.0: @ %entry
; CHECK-AAPCS-NEXT:    .pad #12
; CHECK-AAPCS-NEXT:    sub sp, #12
; CHECK-AAPCS-NEXT:    .save {lr}
; CHECK-AAPCS-NEXT:    push {lr}
; CHECK-AAPCS-NEXT:    mov lr, r11
; CHECK-AAPCS-NEXT:    .save {r11}
; CHECK-AAPCS-NEXT:    push {lr}
; CHECK-AAPCS-NEXT:    .setfp r11, sp
; CHECK-AAPCS-NEXT:    mov r11, sp
; CHECK-AAPCS-NEXT:    .save {r4, r7}
; CHECK-AAPCS-NEXT:    push {r4, r7}
; CHECK-AAPCS-NEXT:    .pad #36
; CHECK-AAPCS-NEXT:    sub sp, #36
; CHECK-AAPCS-NEXT:    mov r4, sp
; CHECK-AAPCS-NEXT:    lsrs r4, r4, #4
; CHECK-AAPCS-NEXT:    lsls r4, r4, #4
; CHECK-AAPCS-NEXT:    mov sp, r4
; CHECK-AAPCS-NEXT:    mov r4, r11
; CHECK-AAPCS-NEXT:    str r1, [r4, #8]
; CHECK-AAPCS-NEXT:    mov r4, r0
; CHECK-AAPCS-NEXT:    mov r0, r11
; CHECK-AAPCS-NEXT:    str r2, [r0, #12]
; CHECK-AAPCS-NEXT:    str r3, [r0, #16]
; CHECK-AAPCS-NEXT:    adds r0, #8
; CHECK-AAPCS-NEXT:    str r0, [sp, #12]
; CHECK-AAPCS-NEXT:    movs r2, #0
; CHECK-AAPCS-NEXT:    str r2, [sp]
; CHECK-AAPCS-NEXT:    str r2, [sp, #4]
; CHECK-AAPCS-NEXT:    add r0, sp, #16
; CHECK-AAPCS-NEXT:    mov r1, r4
; CHECK-AAPCS-NEXT:    mov r3, r2
; CHECK-AAPCS-NEXT:    bl g
; CHECK-AAPCS-NEXT:    mov r7, r11
; CHECK-AAPCS-NEXT:    subs r7, #8
; CHECK-AAPCS-NEXT:    mov sp, r7
; CHECK-AAPCS-NEXT:    pop {r4, r7}
; CHECK-AAPCS-NEXT:    pop {r1}
; CHECK-AAPCS-NEXT:    mov r11, r1
; CHECK-AAPCS-NEXT:    pop {r1}
; CHECK-AAPCS-NEXT:    add sp, #12
; CHECK-AAPCS-NEXT:    bx r1
;
; CHECK-FP-AAPCS-LABEL: test_varargs_realign:
; CHECK-FP-AAPCS:       @ %bb.0: @ %entry
; CHECK-FP-AAPCS-NEXT:    .pad #12
; CHECK-FP-AAPCS-NEXT:    sub sp, #12
; CHECK-FP-AAPCS-NEXT:    .save {lr}
; CHECK-FP-AAPCS-NEXT:    push {lr}
; CHECK-FP-AAPCS-NEXT:    mov lr, r11
; CHECK-FP-AAPCS-NEXT:    .save {r11}
; CHECK-FP-AAPCS-NEXT:    push {lr}
; CHECK-FP-AAPCS-NEXT:    .setfp r11, sp
; CHECK-FP-AAPCS-NEXT:    mov r11, sp
; CHECK-FP-AAPCS-NEXT:    .save {r4, r7}
; CHECK-FP-AAPCS-NEXT:    push {r4, r7}
; CHECK-FP-AAPCS-NEXT:    .pad #36
; CHECK-FP-AAPCS-NEXT:    sub sp, #36
; CHECK-FP-AAPCS-NEXT:    mov r4, sp
; CHECK-FP-AAPCS-NEXT:    lsrs r4, r4, #4
; CHECK-FP-AAPCS-NEXT:    lsls r4, r4, #4
; CHECK-FP-AAPCS-NEXT:    mov sp, r4
; CHECK-FP-AAPCS-NEXT:    mov r4, r11
; CHECK-FP-AAPCS-NEXT:    str r1, [r4, #8]
; CHECK-FP-AAPCS-NEXT:    mov r4, r0
; CHECK-FP-AAPCS-NEXT:    mov r0, r11
; CHECK-FP-AAPCS-NEXT:    str r2, [r0, #12]
; CHECK-FP-AAPCS-NEXT:    str r3, [r0, #16]
; CHECK-FP-AAPCS-NEXT:    adds r0, #8
; CHECK-FP-AAPCS-NEXT:    str r0, [sp, #12]
; CHECK-FP-AAPCS-NEXT:    movs r2, #0
; CHECK-FP-AAPCS-NEXT:    str r2, [sp]
; CHECK-FP-AAPCS-NEXT:    str r2, [sp, #4]
; CHECK-FP-AAPCS-NEXT:    add r0, sp, #16
; CHECK-FP-AAPCS-NEXT:    mov r1, r4
; CHECK-FP-AAPCS-NEXT:    mov r3, r2
; CHECK-FP-AAPCS-NEXT:    bl g
; CHECK-FP-AAPCS-NEXT:    mov r7, r11
; CHECK-FP-AAPCS-NEXT:    subs r7, #8
; CHECK-FP-AAPCS-NEXT:    mov sp, r7
; CHECK-FP-AAPCS-NEXT:    pop {r4, r7}
; CHECK-FP-AAPCS-NEXT:    pop {r1}
; CHECK-FP-AAPCS-NEXT:    mov r11, r1
; CHECK-FP-AAPCS-NEXT:    pop {r1}
; CHECK-FP-AAPCS-NEXT:    add sp, #12
; CHECK-FP-AAPCS-NEXT:    bx r1
entry:
  %v = alloca [4 x i32], align 16
  %ap = alloca %struct.__va_list, align 4
  call void @llvm.va_start(ptr nonnull %ap)
  %call = call i32 @g(ptr nonnull %v, i32 %a, i32 0, i32 0, i32 0, i32 0)
  ret i32 %call
}
; CHECK-LABEL: test_varargs_realign
; Three incoming register varargs
; CHECK:       sub sp, #12
; Setup frame pointer
; CHECK-ATPCS: add r7, sp, #8
; CHECK-AAPCS: mov r11, sp
; Align stack
; CHECK:       mov  r4, sp
; CHECK-NEXT:  lsrs r4, r4, #4
; CHECK-NEXT:  lsls r4, r4, #4
; CHECK-NEXT:  mov  sp, r4
; Incoming register varargs stored via FP
; CHECK-ATPCS: mov r0, r7
; CHECK-ATPCS-NEXT: adds r0, #8
; CHECK-ATPCS-NEXT: stm r0!, {r1, r2, r3}
; CHECK-AAPCS: mov r0, r11
; CHECK-AAPCS: mov r7, r0
; CHECK-AAPCS: adds r7, #8
; CHECK-AAPCS: stm r7!, {r1, r2, r3}
; VLAs present, access via FP
; int test_args_vla(int a, int b, int c, int d, int e) {
;   int v[a];
;   return g(v, a, b, c, d, e);
; }
define dso_local i32 @test_args_vla(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e) local_unnamed_addr  {
; CHECK-ATPCS-LABEL: test_args_vla:
; CHECK-ATPCS:       @ %bb.0: @ %entry
; CHECK-ATPCS-NEXT:    .save {r4, r5, r6, r7, lr}
; CHECK-ATPCS-NEXT:    push {r4, r5, r6, r7, lr}
; CHECK-ATPCS-NEXT:    .setfp r7, sp, #12
; CHECK-ATPCS-NEXT:    add r7, sp, #12
; CHECK-ATPCS-NEXT:    .pad #4
; CHECK-ATPCS-NEXT:    sub sp, #4
; CHECK-ATPCS-NEXT:    mov r6, sp
; CHECK-ATPCS-NEXT:    mov r4, r2
; CHECK-ATPCS-NEXT:    mov r2, r1
; CHECK-ATPCS-NEXT:    mov r1, r0
; CHECK-ATPCS-NEXT:    lsls r0, r0, #2
; CHECK-ATPCS-NEXT:    adds r0, r0, #7
; CHECK-ATPCS-NEXT:    movs r5, #7
; CHECK-ATPCS-NEXT:    bics r0, r5
; CHECK-ATPCS-NEXT:    mov r5, sp
; CHECK-ATPCS-NEXT:    subs r0, r5, r0
; CHECK-ATPCS-NEXT:    mov sp, r0
; CHECK-ATPCS-NEXT:    sub sp, #8
; CHECK-ATPCS-NEXT:    ldr r5, [r7, #8]
; CHECK-ATPCS-NEXT:    str r3, [sp]
; CHECK-ATPCS-NEXT:    str r5, [sp, #4]
; CHECK-ATPCS-NEXT:    mov r3, r4
; CHECK-ATPCS-NEXT:    bl g
; CHECK-ATPCS-NEXT:    add sp, #8
; CHECK-ATPCS-NEXT:    subs r6, r7, #7
; CHECK-ATPCS-NEXT:    subs r6, #5
; CHECK-ATPCS-NEXT:    mov sp, r6
; CHECK-ATPCS-NEXT:    pop {r4, r5, r6, r7, pc}
;
; CHECK-FP-ATPCS-LABEL: test_args_vla:
; CHECK-FP-ATPCS:       @ %bb.0: @ %entry
; CHECK-FP-ATPCS-NEXT:    .save {r4, r5, r6, r7, lr}
; CHECK-FP-ATPCS-NEXT:    push {r4, r5, r6, r7, lr}
; CHECK-FP-ATPCS-NEXT:    .setfp r7, sp, #12
; CHECK-FP-ATPCS-NEXT:    add r7, sp, #12
; CHECK-FP-ATPCS-NEXT:    .pad #4
; CHECK-FP-ATPCS-NEXT:    sub sp, #4
; CHECK-FP-ATPCS-NEXT:    mov r6, sp
; CHECK-FP-ATPCS-NEXT:    mov r4, r2
; CHECK-FP-ATPCS-NEXT:    mov r2, r1
; CHECK-FP-ATPCS-NEXT:    mov r1, r0
; CHECK-FP-ATPCS-NEXT:    lsls r0, r0, #2
; CHECK-FP-ATPCS-NEXT:    adds r0, r0, #7
; CHECK-FP-ATPCS-NEXT:    movs r5, #7
; CHECK-FP-ATPCS-NEXT:    bics r0, r5
; CHECK-FP-ATPCS-NEXT:    mov r5, sp
; CHECK-FP-ATPCS-NEXT:    subs r0, r5, r0
; CHECK-FP-ATPCS-NEXT:    mov sp, r0
; CHECK-FP-ATPCS-NEXT:    sub sp, #8
; CHECK-FP-ATPCS-NEXT:    ldr r5, [r7, #8]
; CHECK-FP-ATPCS-NEXT:    str r3, [sp]
; CHECK-FP-ATPCS-NEXT:    str r5, [sp, #4]
; CHECK-FP-ATPCS-NEXT:    mov r3, r4
; CHECK-FP-ATPCS-NEXT:    bl g
; CHECK-FP-ATPCS-NEXT:    add sp, #8
; CHECK-FP-ATPCS-NEXT:    subs r6, r7, #7
; CHECK-FP-ATPCS-NEXT:    subs r6, #5
; CHECK-FP-ATPCS-NEXT:    mov sp, r6
; CHECK-FP-ATPCS-NEXT:    pop {r4, r5, r6, r7, pc}
;
; CHECK-AAPCS-LABEL: test_args_vla:
; CHECK-AAPCS:       @ %bb.0: @ %entry
; CHECK-AAPCS-NEXT:    .save {lr}
; CHECK-AAPCS-NEXT:    push {lr}
; CHECK-AAPCS-NEXT:    mov lr, r11
; CHECK-AAPCS-NEXT:    .save {r11}
; CHECK-AAPCS-NEXT:    push {lr}
; CHECK-AAPCS-NEXT:    .setfp r11, sp
; CHECK-AAPCS-NEXT:    mov r11, sp
; CHECK-AAPCS-NEXT:    .save {r4, r5, r6, r7}
; CHECK-AAPCS-NEXT:    push {r4, r5, r6, r7}
; CHECK-AAPCS-NEXT:    mov r6, sp
; CHECK-AAPCS-NEXT:    mov r4, r2
; CHECK-AAPCS-NEXT:    mov r2, r1
; CHECK-AAPCS-NEXT:    mov r1, r0
; CHECK-AAPCS-NEXT:    lsls r0, r0, #2
; CHECK-AAPCS-NEXT:    adds r0, r0, #7
; CHECK-AAPCS-NEXT:    movs r5, #7
; CHECK-AAPCS-NEXT:    bics r0, r5
; CHECK-AAPCS-NEXT:    mov r5, sp
; CHECK-AAPCS-NEXT:    subs r0, r5, r0
; CHECK-AAPCS-NEXT:    mov sp, r0
; CHECK-AAPCS-NEXT:    sub sp, #8
; CHECK-AAPCS-NEXT:    mov r5, r11
; CHECK-AAPCS-NEXT:    ldr r5, [r5, #8]
; CHECK-AAPCS-NEXT:    str r3, [sp]
; CHECK-AAPCS-NEXT:    str r5, [sp, #4]
; CHECK-AAPCS-NEXT:    mov r3, r4
; CHECK-AAPCS-NEXT:    bl g
; CHECK-AAPCS-NEXT:    add sp, #8
; CHECK-AAPCS-NEXT:    mov r7, r11
; CHECK-AAPCS-NEXT:    subs r7, #16
; CHECK-AAPCS-NEXT:    mov sp, r7
; CHECK-AAPCS-NEXT:    pop {r4, r5, r6, r7}
; CHECK-AAPCS-NEXT:    pop {r1}
; CHECK-AAPCS-NEXT:    mov r11, r1
; CHECK-AAPCS-NEXT:    pop {pc}
;
; CHECK-FP-AAPCS-LABEL: test_args_vla:
; CHECK-FP-AAPCS:       @ %bb.0: @ %entry
; CHECK-FP-AAPCS-NEXT:    .save {lr}
; CHECK-FP-AAPCS-NEXT:    push {lr}
; CHECK-FP-AAPCS-NEXT:    mov lr, r11
; CHECK-FP-AAPCS-NEXT:    .save {r11}
; CHECK-FP-AAPCS-NEXT:    push {lr}
; CHECK-FP-AAPCS-NEXT:    .setfp r11, sp
; CHECK-FP-AAPCS-NEXT:    mov r11, sp
; CHECK-FP-AAPCS-NEXT:    .save {r4, r5, r6, r7}
; CHECK-FP-AAPCS-NEXT:    push {r4, r5, r6, r7}
; CHECK-FP-AAPCS-NEXT:    mov r6, sp
; CHECK-FP-AAPCS-NEXT:    mov r4, r2
; CHECK-FP-AAPCS-NEXT:    mov r2, r1
; CHECK-FP-AAPCS-NEXT:    mov r1, r0
; CHECK-FP-AAPCS-NEXT:    lsls r0, r0, #2
; CHECK-FP-AAPCS-NEXT:    adds r0, r0, #7
; CHECK-FP-AAPCS-NEXT:    movs r5, #7
; CHECK-FP-AAPCS-NEXT:    bics r0, r5
; CHECK-FP-AAPCS-NEXT:    mov r5, sp
; CHECK-FP-AAPCS-NEXT:    subs r0, r5, r0
; CHECK-FP-AAPCS-NEXT:    mov sp, r0
; CHECK-FP-AAPCS-NEXT:    sub sp, #8
; CHECK-FP-AAPCS-NEXT:    mov r5, r11
; CHECK-FP-AAPCS-NEXT:    ldr r5, [r5, #8]
; CHECK-FP-AAPCS-NEXT:    str r3, [sp]
; CHECK-FP-AAPCS-NEXT:    str r5, [sp, #4]
; CHECK-FP-AAPCS-NEXT:    mov r3, r4
; CHECK-FP-AAPCS-NEXT:    bl g
; CHECK-FP-AAPCS-NEXT:    add sp, #8
; CHECK-FP-AAPCS-NEXT:    mov r7, r11
; CHECK-FP-AAPCS-NEXT:    subs r7, #16
; CHECK-FP-AAPCS-NEXT:    mov sp, r7
; CHECK-FP-AAPCS-NEXT:    pop {r4, r5, r6, r7}
; CHECK-FP-AAPCS-NEXT:    pop {r1}
; CHECK-FP-AAPCS-NEXT:    mov r11, r1
; CHECK-FP-AAPCS-NEXT:    pop {pc}
entry:
  %vla = alloca i32, i32 %a, align 4
  %call = call i32 @g(ptr nonnull %vla, i32 %a, i32 %b, i32 %c, i32 %d, i32 %e)
  ret i32 %call
}
; CHECK-LABEL: test_args_vla
; Setup frame pointer
; CHECK-ATPCS: add r7, sp, #12
; CHECK-AAPCS: mov r11, sp
; Allocate outgoing stack arguments space
; CHECK:       sub sp, #8
; Load `e` via FP
; CHECK-ATPCS: ldr r5, [r7, #8]
; CHECK-AAPCS: mov r5, r11
; CHECK-AAPCS: ldr r5, [r5, #8]
; Pass `d` and `e` as arguments
; CHECK-NEXT:  str r3, [sp]
; CHECK-NEXT:  str r5, [sp, #4]
; CHECK:       bl  g

; int test_varargs_vla(int a, ...) {
;   int v[a];
;   __builtin_va_list ap;
;   __builtin_va_start(ap, a);
;   return g(v, a, 0, 0, 0, 0);
; }
define dso_local i32 @test_varargs_vla(i32 %a, ...) local_unnamed_addr  {
; CHECK-ATPCS-LABEL: test_varargs_vla:
; CHECK-ATPCS:       @ %bb.0: @ %entry
; CHECK-ATPCS-NEXT:    .pad #12
; CHECK-ATPCS-NEXT:    sub sp, #12
; CHECK-ATPCS-NEXT:    .save {r4, r6, r7, lr}
; CHECK-ATPCS-NEXT:    push {r4, r6, r7, lr}
; CHECK-ATPCS-NEXT:    .setfp r7, sp, #8
; CHECK-ATPCS-NEXT:    add r7, sp, #8
; CHECK-ATPCS-NEXT:    .pad #4
; CHECK-ATPCS-NEXT:    sub sp, #4
; CHECK-ATPCS-NEXT:    mov r6, sp
; CHECK-ATPCS-NEXT:    mov r4, r0
; CHECK-ATPCS-NEXT:    str r1, [r7, #8]
; CHECK-ATPCS-NEXT:    str r2, [r7, #12]
; CHECK-ATPCS-NEXT:    str r3, [r7, #16]
; CHECK-ATPCS-NEXT:    lsls r0, r0, #2
; CHECK-ATPCS-NEXT:    adds r0, r0, #7
; CHECK-ATPCS-NEXT:    movs r1, #7
; CHECK-ATPCS-NEXT:    bics r0, r1
; CHECK-ATPCS-NEXT:    mov r1, sp
; CHECK-ATPCS-NEXT:    subs r0, r1, r0
; CHECK-ATPCS-NEXT:    mov sp, r0
; CHECK-ATPCS-NEXT:    adds r1, r7, #7
; CHECK-ATPCS-NEXT:    adds r1, #1
; CHECK-ATPCS-NEXT:    str r1, [r6]
; CHECK-ATPCS-NEXT:    sub sp, #8
; CHECK-ATPCS-NEXT:    movs r2, #0
; CHECK-ATPCS-NEXT:    str r2, [sp]
; CHECK-ATPCS-NEXT:    str r2, [sp, #4]
; CHECK-ATPCS-NEXT:    mov r1, r4
; CHECK-ATPCS-NEXT:    mov r3, r2
; CHECK-ATPCS-NEXT:    bl g
; CHECK-ATPCS-NEXT:    add sp, #8
; CHECK-ATPCS-NEXT:    subs r6, r7, #7
; CHECK-ATPCS-NEXT:    subs r6, #1
; CHECK-ATPCS-NEXT:    mov sp, r6
; CHECK-ATPCS-NEXT:    pop {r4, r6, r7}
; CHECK-ATPCS-NEXT:    pop {r1}
; CHECK-ATPCS-NEXT:    add sp, #12
; CHECK-ATPCS-NEXT:    bx r1
;
; CHECK-FP-ATPCS-LABEL: test_varargs_vla:
; CHECK-FP-ATPCS:       @ %bb.0: @ %entry
; CHECK-FP-ATPCS-NEXT:    .pad #12
; CHECK-FP-ATPCS-NEXT:    sub sp, #12
; CHECK-FP-ATPCS-NEXT:    .save {r4, r6, r7, lr}
; CHECK-FP-ATPCS-NEXT:    push {r4, r6, r7, lr}
; CHECK-FP-ATPCS-NEXT:    .setfp r7, sp, #8
; CHECK-FP-ATPCS-NEXT:    add r7, sp, #8
; CHECK-FP-ATPCS-NEXT:    .pad #4
; CHECK-FP-ATPCS-NEXT:    sub sp, #4
; CHECK-FP-ATPCS-NEXT:    mov r6, sp
; CHECK-FP-ATPCS-NEXT:    mov r4, r0
; CHECK-FP-ATPCS-NEXT:    str r1, [r7, #8]
; CHECK-FP-ATPCS-NEXT:    str r2, [r7, #12]
; CHECK-FP-ATPCS-NEXT:    str r3, [r7, #16]
; CHECK-FP-ATPCS-NEXT:    lsls r0, r0, #2
; CHECK-FP-ATPCS-NEXT:    adds r0, r0, #7
; CHECK-FP-ATPCS-NEXT:    movs r1, #7
; CHECK-FP-ATPCS-NEXT:    bics r0, r1
; CHECK-FP-ATPCS-NEXT:    mov r1, sp
; CHECK-FP-ATPCS-NEXT:    subs r0, r1, r0
; CHECK-FP-ATPCS-NEXT:    mov sp, r0
; CHECK-FP-ATPCS-NEXT:    adds r1, r7, #7
; CHECK-FP-ATPCS-NEXT:    adds r1, #1
; CHECK-FP-ATPCS-NEXT:    str r1, [r6]
; CHECK-FP-ATPCS-NEXT:    sub sp, #8
; CHECK-FP-ATPCS-NEXT:    movs r2, #0
; CHECK-FP-ATPCS-NEXT:    str r2, [sp]
; CHECK-FP-ATPCS-NEXT:    str r2, [sp, #4]
; CHECK-FP-ATPCS-NEXT:    mov r1, r4
; CHECK-FP-ATPCS-NEXT:    mov r3, r2
; CHECK-FP-ATPCS-NEXT:    bl g
; CHECK-FP-ATPCS-NEXT:    add sp, #8
; CHECK-FP-ATPCS-NEXT:    subs r6, r7, #7
; CHECK-FP-ATPCS-NEXT:    subs r6, #1
; CHECK-FP-ATPCS-NEXT:    mov sp, r6
; CHECK-FP-ATPCS-NEXT:    pop {r4, r6, r7}
; CHECK-FP-ATPCS-NEXT:    pop {r1}
; CHECK-FP-ATPCS-NEXT:    add sp, #12
; CHECK-FP-ATPCS-NEXT:    bx r1
;
; CHECK-AAPCS-LABEL: test_varargs_vla:
; CHECK-AAPCS:       @ %bb.0: @ %entry
; CHECK-AAPCS-NEXT:    .pad #12
; CHECK-AAPCS-NEXT:    sub sp, #12
; CHECK-AAPCS-NEXT:    .save {lr}
; CHECK-AAPCS-NEXT:    push {lr}
; CHECK-AAPCS-NEXT:    mov lr, r11
; CHECK-AAPCS-NEXT:    .save {r11}
; CHECK-AAPCS-NEXT:    push {lr}
; CHECK-AAPCS-NEXT:    .setfp r11, sp
; CHECK-AAPCS-NEXT:    mov r11, sp
; CHECK-AAPCS-NEXT:    .save {r4, r5, r6, r7}
; CHECK-AAPCS-NEXT:    push {r4, r5, r6, r7}
; CHECK-AAPCS-NEXT:    .pad #4
; CHECK-AAPCS-NEXT:    sub sp, #4
; CHECK-AAPCS-NEXT:    mov r6, sp
; CHECK-AAPCS-NEXT:    mov r4, r0
; CHECK-AAPCS-NEXT:    mov r5, r11
; CHECK-AAPCS-NEXT:    str r1, [r5, #8]
; CHECK-AAPCS-NEXT:    mov r1, r11
; CHECK-AAPCS-NEXT:    str r2, [r1, #12]
; CHECK-AAPCS-NEXT:    str r3, [r1, #16]
; CHECK-AAPCS-NEXT:    lsls r0, r0, #2
; CHECK-AAPCS-NEXT:    adds r0, r0, #7
; CHECK-AAPCS-NEXT:    movs r1, #7
; CHECK-AAPCS-NEXT:    bics r0, r1
; CHECK-AAPCS-NEXT:    mov r1, sp
; CHECK-AAPCS-NEXT:    subs r0, r1, r0
; CHECK-AAPCS-NEXT:    mov sp, r0
; CHECK-AAPCS-NEXT:    mov r1, r11
; CHECK-AAPCS-NEXT:    adds r1, #8
; CHECK-AAPCS-NEXT:    str r1, [r6]
; CHECK-AAPCS-NEXT:    sub sp, #8
; CHECK-AAPCS-NEXT:    movs r2, #0
; CHECK-AAPCS-NEXT:    str r2, [sp]
; CHECK-AAPCS-NEXT:    str r2, [sp, #4]
; CHECK-AAPCS-NEXT:    mov r1, r4
; CHECK-AAPCS-NEXT:    mov r3, r2
; CHECK-AAPCS-NEXT:    bl g
; CHECK-AAPCS-NEXT:    add sp, #8
; CHECK-AAPCS-NEXT:    mov r7, r11
; CHECK-AAPCS-NEXT:    subs r7, #16
; CHECK-AAPCS-NEXT:    mov sp, r7
; CHECK-AAPCS-NEXT:    pop {r4, r5, r6, r7}
; CHECK-AAPCS-NEXT:    pop {r1}
; CHECK-AAPCS-NEXT:    mov r11, r1
; CHECK-AAPCS-NEXT:    pop {r1}
; CHECK-AAPCS-NEXT:    add sp, #12
; CHECK-AAPCS-NEXT:    bx r1
;
; CHECK-FP-AAPCS-LABEL: test_varargs_vla:
; CHECK-FP-AAPCS:       @ %bb.0: @ %entry
; CHECK-FP-AAPCS-NEXT:    .pad #12
; CHECK-FP-AAPCS-NEXT:    sub sp, #12
; CHECK-FP-AAPCS-NEXT:    .save {lr}
; CHECK-FP-AAPCS-NEXT:    push {lr}
; CHECK-FP-AAPCS-NEXT:    mov lr, r11
; CHECK-FP-AAPCS-NEXT:    .save {r11}
; CHECK-FP-AAPCS-NEXT:    push {lr}
; CHECK-FP-AAPCS-NEXT:    .setfp r11, sp
; CHECK-FP-AAPCS-NEXT:    mov r11, sp
; CHECK-FP-AAPCS-NEXT:    .save {r4, r5, r6, r7}
; CHECK-FP-AAPCS-NEXT:    push {r4, r5, r6, r7}
; CHECK-FP-AAPCS-NEXT:    .pad #4
; CHECK-FP-AAPCS-NEXT:    sub sp, #4
; CHECK-FP-AAPCS-NEXT:    mov r6, sp
; CHECK-FP-AAPCS-NEXT:    mov r4, r0
; CHECK-FP-AAPCS-NEXT:    mov r5, r11
; CHECK-FP-AAPCS-NEXT:    str r1, [r5, #8]
; CHECK-FP-AAPCS-NEXT:    mov r1, r11
; CHECK-FP-AAPCS-NEXT:    str r2, [r1, #12]
; CHECK-FP-AAPCS-NEXT:    str r3, [r1, #16]
; CHECK-FP-AAPCS-NEXT:    lsls r0, r0, #2
; CHECK-FP-AAPCS-NEXT:    adds r0, r0, #7
; CHECK-FP-AAPCS-NEXT:    movs r1, #7
; CHECK-FP-AAPCS-NEXT:    bics r0, r1
; CHECK-FP-AAPCS-NEXT:    mov r1, sp
; CHECK-FP-AAPCS-NEXT:    subs r0, r1, r0
; CHECK-FP-AAPCS-NEXT:    mov sp, r0
; CHECK-FP-AAPCS-NEXT:    mov r1, r11
; CHECK-FP-AAPCS-NEXT:    adds r1, #8
; CHECK-FP-AAPCS-NEXT:    str r1, [r6]
; CHECK-FP-AAPCS-NEXT:    sub sp, #8
; CHECK-FP-AAPCS-NEXT:    movs r2, #0
; CHECK-FP-AAPCS-NEXT:    str r2, [sp]
; CHECK-FP-AAPCS-NEXT:    str r2, [sp, #4]
; CHECK-FP-AAPCS-NEXT:    mov r1, r4
; CHECK-FP-AAPCS-NEXT:    mov r3, r2
; CHECK-FP-AAPCS-NEXT:    bl g
; CHECK-FP-AAPCS-NEXT:    add sp, #8
; CHECK-FP-AAPCS-NEXT:    mov r7, r11
; CHECK-FP-AAPCS-NEXT:    subs r7, #16
; CHECK-FP-AAPCS-NEXT:    mov sp, r7
; CHECK-FP-AAPCS-NEXT:    pop {r4, r5, r6, r7}
; CHECK-FP-AAPCS-NEXT:    pop {r1}
; CHECK-FP-AAPCS-NEXT:    mov r11, r1
; CHECK-FP-AAPCS-NEXT:    pop {r1}
; CHECK-FP-AAPCS-NEXT:    add sp, #12
; CHECK-FP-AAPCS-NEXT:    bx r1
entry:
  %ap = alloca %struct.__va_list, align 4
  %vla = alloca i32, i32 %a, align 4
  call void @llvm.va_start(ptr nonnull %ap)
  %call = call i32 @g(ptr nonnull %vla, i32 %a, i32 0, i32 0, i32 0, i32 0)
  ret i32 %call
}
; CHECK-LABEL: test_varargs_vla
; Three incoming register varargs
; CHECK:       sub sp, #12
; Setup frame pointer
; CHECK-ATPCS: add r7, sp, #8
; CHECK-AAPCS: mov r11, sp
; Register varargs stored via FP
; CHECK-ATPCS-DAG:  str r3, [r7, #16]
; CHECK-ATPCS-DAG:  str r2, [r7, #12]
; CHECK-ATPCS-DAG:  str r1, [r7, #8]
; CHECK-AAPCS-DAG:  mov r5, r11
; CHECK-AAPCS-DAG:  str r1, [r5, #8]
; CHECK-AAPCS-DAG:  mov r1, r11
; CHECK-AAPCS-DAG:  str r3, [r1, #16]
; CHECK-AAPCS-DAG:  mov r1, r11
; CHECK-AAPCS-DAG:  str r2, [r1, #12]

; Moving SP, access via SP
; int test_args_moving_sp(int a, int b, int c, int d, int e) {
;   int v[4];
;   return f(v, a, b + c + d, e, s) + h(v, v+1, v+2);
; }
define dso_local i32 @test_args_moving_sp(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e) local_unnamed_addr  {
; CHECK-NOFP-LABEL: test_args_moving_sp:
; CHECK-NOFP:       @ %bb.0: @ %entry
; CHECK-NOFP-NEXT:    .save {r4, r5, r6, r7, lr}
; CHECK-NOFP-NEXT:    push {r4, r5, r6, r7, lr}
; CHECK-NOFP-NEXT:    .pad #20
; CHECK-NOFP-NEXT:    sub sp, #20
; CHECK-NOFP-NEXT:    mov r6, sp
; CHECK-NOFP-NEXT:    str r0, [r6] @ 4-byte Spill
; CHECK-NOFP-NEXT:    sub sp, #508
; CHECK-NOFP-NEXT:    sub sp, #4
; CHECK-NOFP-NEXT:    ldr r0, .LCPI6_0
; CHECK-NOFP-NEXT:    mov r5, sp
; CHECK-NOFP-NEXT:    ldr r7, .LCPI6_1
; CHECK-NOFP-NEXT:  .LBB6_1: @ %entry
; CHECK-NOFP-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-NOFP-NEXT:    ldr r4, [r0]
; CHECK-NOFP-NEXT:    adds r0, #4
; CHECK-NOFP-NEXT:    str r4, [r5]
; CHECK-NOFP-NEXT:    adds r5, #4
; CHECK-NOFP-NEXT:    subs r7, #4
; CHECK-NOFP-NEXT:    bne .LBB6_1
; CHECK-NOFP-NEXT:  @ %bb.2: @ %entry
; CHECK-NOFP-NEXT:    adds r0, r2, r1
; CHECK-NOFP-NEXT:    adds r2, r0, r3
; CHECK-NOFP-NEXT:    adds r5, r6, #4
; CHECK-NOFP-NEXT:    ldr r3, [r6, #40]
; CHECK-NOFP-NEXT:    mov r0, r5
; CHECK-NOFP-NEXT:    ldr r1, [r6] @ 4-byte Reload
; CHECK-NOFP-NEXT:    bl f
; CHECK-NOFP-NEXT:    add sp, #508
; CHECK-NOFP-NEXT:    add sp, #4
; CHECK-NOFP-NEXT:    mov r4, r0
; CHECK-NOFP-NEXT:    adds r1, r5, #4
; CHECK-NOFP-NEXT:    mov r2, r5
; CHECK-NOFP-NEXT:    adds r2, #8
; CHECK-NOFP-NEXT:    mov r0, r5
; CHECK-NOFP-NEXT:    bl h
; CHECK-NOFP-NEXT:    adds r0, r0, r4
; CHECK-NOFP-NEXT:    add sp, #20
; CHECK-NOFP-NEXT:    pop {r4, r5, r6, r7, pc}
; CHECK-NOFP-NEXT:    .p2align 2
; CHECK-NOFP-NEXT:  @ %bb.3:
; CHECK-NOFP-NEXT:  .LCPI6_0:
; CHECK-NOFP-NEXT:    .long s
; CHECK-NOFP-NEXT:  .LCPI6_1:
; CHECK-NOFP-NEXT:    .long 512 @ 0x200
;
; CHECK-FP-ATPCS-LABEL: test_args_moving_sp:
; CHECK-FP-ATPCS:       @ %bb.0: @ %entry
; CHECK-FP-ATPCS-NEXT:    .save {r4, r5, r6, r7, lr}
; CHECK-FP-ATPCS-NEXT:    push {r4, r5, r6, r7, lr}
; CHECK-FP-ATPCS-NEXT:    .setfp r7, sp, #12
; CHECK-FP-ATPCS-NEXT:    add r7, sp, #12
; CHECK-FP-ATPCS-NEXT:    .pad #28
; CHECK-FP-ATPCS-NEXT:    sub sp, #28
; CHECK-FP-ATPCS-NEXT:    mov r6, sp
; CHECK-FP-ATPCS-NEXT:    str r3, [r6, #4] @ 4-byte Spill
; CHECK-FP-ATPCS-NEXT:    str r0, [r6, #8] @ 4-byte Spill
; CHECK-FP-ATPCS-NEXT:    sub sp, #508
; CHECK-FP-ATPCS-NEXT:    sub sp, #4
; CHECK-FP-ATPCS-NEXT:    ldr r0, .LCPI6_0
; CHECK-FP-ATPCS-NEXT:    mov r5, sp
; CHECK-FP-ATPCS-NEXT:    ldr r4, .LCPI6_1
; CHECK-FP-ATPCS-NEXT:  .LBB6_1: @ %entry
; CHECK-FP-ATPCS-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-FP-ATPCS-NEXT:    ldr r3, [r0]
; CHECK-FP-ATPCS-NEXT:    adds r0, #4
; CHECK-FP-ATPCS-NEXT:    str r3, [r5]
; CHECK-FP-ATPCS-NEXT:    adds r5, #4
; CHECK-FP-ATPCS-NEXT:    subs r4, #4
; CHECK-FP-ATPCS-NEXT:    bne .LBB6_1
; CHECK-FP-ATPCS-NEXT:  @ %bb.2: @ %entry
; CHECK-FP-ATPCS-NEXT:    adds r0, r2, r1
; CHECK-FP-ATPCS-NEXT:    ldr r1, [r6, #4] @ 4-byte Reload
; CHECK-FP-ATPCS-NEXT:    adds r2, r0, r1
; CHECK-FP-ATPCS-NEXT:    adds r5, r6, #7
; CHECK-FP-ATPCS-NEXT:    adds r5, #5
; CHECK-FP-ATPCS-NEXT:    ldr r3, [r7, #8]
; CHECK-FP-ATPCS-NEXT:    mov r0, r5
; CHECK-FP-ATPCS-NEXT:    ldr r1, [r6, #8] @ 4-byte Reload
; CHECK-FP-ATPCS-NEXT:    bl f
; CHECK-FP-ATPCS-NEXT:    add sp, #508
; CHECK-FP-ATPCS-NEXT:    add sp, #4
; CHECK-FP-ATPCS-NEXT:    mov r4, r0
; CHECK-FP-ATPCS-NEXT:    adds r1, r5, #4
; CHECK-FP-ATPCS-NEXT:    mov r2, r5
; CHECK-FP-ATPCS-NEXT:    adds r2, #8
; CHECK-FP-ATPCS-NEXT:    mov r0, r5
; CHECK-FP-ATPCS-NEXT:    bl h
; CHECK-FP-ATPCS-NEXT:    adds r0, r0, r4
; CHECK-FP-ATPCS-NEXT:    add sp, #28
; CHECK-FP-ATPCS-NEXT:    pop {r4, r5, r6, r7, pc}
; CHECK-FP-ATPCS-NEXT:    .p2align 2
; CHECK-FP-ATPCS-NEXT:  @ %bb.3:
; CHECK-FP-ATPCS-NEXT:  .LCPI6_0:
; CHECK-FP-ATPCS-NEXT:    .long s
; CHECK-FP-ATPCS-NEXT:  .LCPI6_1:
; CHECK-FP-ATPCS-NEXT:    .long 512 @ 0x200
;
; CHECK-FP-AAPCS-LABEL: test_args_moving_sp:
; CHECK-FP-AAPCS:       @ %bb.0: @ %entry
; CHECK-FP-AAPCS-NEXT:    .save {lr}
; CHECK-FP-AAPCS-NEXT:    push {lr}
; CHECK-FP-AAPCS-NEXT:    mov lr, r11
; CHECK-FP-AAPCS-NEXT:    .save {r11}
; CHECK-FP-AAPCS-NEXT:    push {lr}
; CHECK-FP-AAPCS-NEXT:    .setfp r11, sp
; CHECK-FP-AAPCS-NEXT:    mov r11, sp
; CHECK-FP-AAPCS-NEXT:    .save {r4, r5, r6, r7}
; CHECK-FP-AAPCS-NEXT:    push {r4, r5, r6, r7}
; CHECK-FP-AAPCS-NEXT:    .pad #24
; CHECK-FP-AAPCS-NEXT:    sub sp, #24
; CHECK-FP-AAPCS-NEXT:    mov r6, sp
; CHECK-FP-AAPCS-NEXT:    str r0, [r6, #4] @ 4-byte Spill
; CHECK-FP-AAPCS-NEXT:    sub sp, #508
; CHECK-FP-AAPCS-NEXT:    sub sp, #4
; CHECK-FP-AAPCS-NEXT:    ldr r0, .LCPI6_0
; CHECK-FP-AAPCS-NEXT:    mov r5, sp
; CHECK-FP-AAPCS-NEXT:    ldr r7, .LCPI6_1
; CHECK-FP-AAPCS-NEXT:  .LBB6_1: @ %entry
; CHECK-FP-AAPCS-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-FP-AAPCS-NEXT:    ldr r4, [r0]
; CHECK-FP-AAPCS-NEXT:    adds r0, #4
; CHECK-FP-AAPCS-NEXT:    str r4, [r5]
; CHECK-FP-AAPCS-NEXT:    adds r5, #4
; CHECK-FP-AAPCS-NEXT:    subs r7, #4
; CHECK-FP-AAPCS-NEXT:    bne .LBB6_1
; CHECK-FP-AAPCS-NEXT:  @ %bb.2: @ %entry
; CHECK-FP-AAPCS-NEXT:    adds r0, r2, r1
; CHECK-FP-AAPCS-NEXT:    adds r2, r0, r3
; CHECK-FP-AAPCS-NEXT:    adds r5, r6, #7
; CHECK-FP-AAPCS-NEXT:    adds r5, #1
; CHECK-FP-AAPCS-NEXT:    mov r0, r11
; CHECK-FP-AAPCS-NEXT:    ldr r3, [r0, #8]
; CHECK-FP-AAPCS-NEXT:    mov r0, r5
; CHECK-FP-AAPCS-NEXT:    ldr r1, [r6, #4] @ 4-byte Reload
; CHECK-FP-AAPCS-NEXT:    bl f
; CHECK-FP-AAPCS-NEXT:    add sp, #508
; CHECK-FP-AAPCS-NEXT:    add sp, #4
; CHECK-FP-AAPCS-NEXT:    mov r4, r0
; CHECK-FP-AAPCS-NEXT:    adds r1, r5, #4
; CHECK-FP-AAPCS-NEXT:    mov r2, r5
; CHECK-FP-AAPCS-NEXT:    adds r2, #8
; CHECK-FP-AAPCS-NEXT:    mov r0, r5
; CHECK-FP-AAPCS-NEXT:    bl h
; CHECK-FP-AAPCS-NEXT:    adds r0, r0, r4
; CHECK-FP-AAPCS-NEXT:    add sp, #24
; CHECK-FP-AAPCS-NEXT:    pop {r4, r5, r6, r7}
; CHECK-FP-AAPCS-NEXT:    pop {r1}
; CHECK-FP-AAPCS-NEXT:    mov r11, r1
; CHECK-FP-AAPCS-NEXT:    pop {pc}
; CHECK-FP-AAPCS-NEXT:    .p2align 2
; CHECK-FP-AAPCS-NEXT:  @ %bb.3:
; CHECK-FP-AAPCS-NEXT:  .LCPI6_0:
; CHECK-FP-AAPCS-NEXT:    .long s
; CHECK-FP-AAPCS-NEXT:  .LCPI6_1:
; CHECK-FP-AAPCS-NEXT:    .long 512 @ 0x200
entry:
  %v = alloca [4 x i32], align 4
  %add = add nsw i32 %c, %b
  %add1 = add nsw i32 %add, %d
  %call = call i32 @f(ptr nonnull %v, i32 %a, i32 %add1, i32 %e, ptr byval(%struct.S) nonnull align 4 @s)
  %add.ptr = getelementptr inbounds [4 x i32], ptr %v, i32 0, i32 1
  %add.ptr5 = getelementptr inbounds [4 x i32], ptr %v, i32 0, i32 2
  %call6 = call i32 @h(ptr nonnull %v, ptr nonnull %add.ptr, ptr nonnull %add.ptr5)
  %add7 = add nsw i32 %call6, %call
  ret i32 %add7
}
; CHECK-LABEL: test_args_moving_sp
; 20 bytes callee-saved area without FP
; CHECK-NOFP: push {r4, r5, r6, r7, lr}
; 20 bytes callee-saved area for ATPCS
; CHECK-FP-ATPCS: push {r4, r5, r6, r7, lr}
; 24 bytes callee-saved area for AAPCS as codegen prefers an even number of GPRs spilled
; CHECK-FP-AAPCS: push {lr}
; CHECK-FP-AAPCS: mov lr, r11
; CHECK-FP-AAPCS: push {lr}
; CHECK-FP-AAPCS: push {r4, r5, r6, r7}
; 20 bytes locals without FP
; CHECK-NOFP:       sub sp, #20
; 28 bytes locals with FP for ATPCS
; CHECK-FP-ATPCS:       sub sp, #28
; 24 bytes locals with FP for AAPCS
; CHECK-FP-AAPCS:       sub sp, #24
; Setup base pointer
; CHECK:       mov r6, sp
; Allocate outgoing arguments space
; CHECK:       sub sp, #508
; CHECK:       sub sp, #4
; Load `e` via BP if FP is not present (40 = 20 + 20)
; CHECK-NOFP:  ldr r3, [r6, #40]
; Load `e` via FP otherwise
; CHECK-FP-ATPCS: ldr r3, [r7, #8]
; CHECK-FP-AAPCS: mov r0, r11
; CHECK-FP-AAPCS: ldr r3, [r0, #8]
; CHECK:       bl  f
; Stack restored before next call
; CHECK-NEXT:  add sp, #508
; CHECK-NEXT:  add sp, #4
; CHECK:       bl  h

; int test_varargs_moving_sp(int a, ...) {
;   int v[4];
;   __builtin_va_list ap;
;   __builtin_va_start(ap, a);
;   return f(v, a, 0, 0, s) + h(v, v+1, v+2);
; }
define dso_local i32 @test_varargs_moving_sp(i32 %a, ...) local_unnamed_addr  {
; CHECK-NOFP-LABEL: test_varargs_moving_sp:
; CHECK-NOFP:       @ %bb.0: @ %entry
; CHECK-NOFP-NEXT:    .pad #12
; CHECK-NOFP-NEXT:    sub sp, #12
; CHECK-NOFP-NEXT:    .save {r4, r5, r6, lr}
; CHECK-NOFP-NEXT:    push {r4, r5, r6, lr}
; CHECK-NOFP-NEXT:    .pad #20
; CHECK-NOFP-NEXT:    sub sp, #20
; CHECK-NOFP-NEXT:    mov r6, sp
; CHECK-NOFP-NEXT:    mov r4, r0
; CHECK-NOFP-NEXT:    mov r0, r6
; CHECK-NOFP-NEXT:    adds r0, #36
; CHECK-NOFP-NEXT:    stm r0!, {r1, r2, r3}
; CHECK-NOFP-NEXT:    adds r0, r6, #7
; CHECK-NOFP-NEXT:    adds r0, #29
; CHECK-NOFP-NEXT:    str r0, [r6]
; CHECK-NOFP-NEXT:    sub sp, #508
; CHECK-NOFP-NEXT:    sub sp, #4
; CHECK-NOFP-NEXT:    ldr r0, .LCPI7_0
; CHECK-NOFP-NEXT:    mov r1, sp
; CHECK-NOFP-NEXT:    ldr r2, .LCPI7_1
; CHECK-NOFP-NEXT:  .LBB7_1: @ %entry
; CHECK-NOFP-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-NOFP-NEXT:    ldr r3, [r0]
; CHECK-NOFP-NEXT:    adds r0, #4
; CHECK-NOFP-NEXT:    str r3, [r1]
; CHECK-NOFP-NEXT:    adds r1, #4
; CHECK-NOFP-NEXT:    subs r2, #4
; CHECK-NOFP-NEXT:    bne .LBB7_1
; CHECK-NOFP-NEXT:  @ %bb.2: @ %entry
; CHECK-NOFP-NEXT:    adds r5, r6, #4
; CHECK-NOFP-NEXT:    movs r2, #0
; CHECK-NOFP-NEXT:    mov r0, r5
; CHECK-NOFP-NEXT:    mov r1, r4
; CHECK-NOFP-NEXT:    mov r3, r2
; CHECK-NOFP-NEXT:    bl f
; CHECK-NOFP-NEXT:    add sp, #508
; CHECK-NOFP-NEXT:    add sp, #4
; CHECK-NOFP-NEXT:    mov r4, r0
; CHECK-NOFP-NEXT:    adds r1, r5, #4
; CHECK-NOFP-NEXT:    mov r2, r5
; CHECK-NOFP-NEXT:    adds r2, #8
; CHECK-NOFP-NEXT:    mov r0, r5
; CHECK-NOFP-NEXT:    bl h
; CHECK-NOFP-NEXT:    adds r0, r0, r4
; CHECK-NOFP-NEXT:    add sp, #20
; CHECK-NOFP-NEXT:    pop {r4, r5, r6}
; CHECK-NOFP-NEXT:    pop {r1}
; CHECK-NOFP-NEXT:    add sp, #12
; CHECK-NOFP-NEXT:    bx r1
; CHECK-NOFP-NEXT:    .p2align 2
; CHECK-NOFP-NEXT:  @ %bb.3:
; CHECK-NOFP-NEXT:  .LCPI7_0:
; CHECK-NOFP-NEXT:    .long s
; CHECK-NOFP-NEXT:  .LCPI7_1:
; CHECK-NOFP-NEXT:    .long 512 @ 0x200
;
; CHECK-FP-ATPCS-LABEL: test_varargs_moving_sp:
; CHECK-FP-ATPCS:       @ %bb.0: @ %entry
; CHECK-FP-ATPCS-NEXT:    .pad #12
; CHECK-FP-ATPCS-NEXT:    sub sp, #12
; CHECK-FP-ATPCS-NEXT:    .save {r4, r5, r6, r7, lr}
; CHECK-FP-ATPCS-NEXT:    push {r4, r5, r6, r7, lr}
; CHECK-FP-ATPCS-NEXT:    .setfp r7, sp, #12
; CHECK-FP-ATPCS-NEXT:    add r7, sp, #12
; CHECK-FP-ATPCS-NEXT:    .pad #24
; CHECK-FP-ATPCS-NEXT:    sub sp, #24
; CHECK-FP-ATPCS-NEXT:    mov r6, sp
; CHECK-FP-ATPCS-NEXT:    mov r5, r0
; CHECK-FP-ATPCS-NEXT:    mov r0, r7
; CHECK-FP-ATPCS-NEXT:    adds r0, #8
; CHECK-FP-ATPCS-NEXT:    stm r0!, {r1, r2, r3}
; CHECK-FP-ATPCS-NEXT:    adds r0, r7, #7
; CHECK-FP-ATPCS-NEXT:    adds r0, #1
; CHECK-FP-ATPCS-NEXT:    str r0, [r6, #4]
; CHECK-FP-ATPCS-NEXT:    sub sp, #508
; CHECK-FP-ATPCS-NEXT:    sub sp, #4
; CHECK-FP-ATPCS-NEXT:    ldr r0, .LCPI7_0
; CHECK-FP-ATPCS-NEXT:    mov r1, sp
; CHECK-FP-ATPCS-NEXT:    ldr r2, .LCPI7_1
; CHECK-FP-ATPCS-NEXT:  .LBB7_1: @ %entry
; CHECK-FP-ATPCS-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-FP-ATPCS-NEXT:    ldr r3, [r0]
; CHECK-FP-ATPCS-NEXT:    adds r0, #4
; CHECK-FP-ATPCS-NEXT:    str r3, [r1]
; CHECK-FP-ATPCS-NEXT:    adds r1, #4
; CHECK-FP-ATPCS-NEXT:    subs r2, #4
; CHECK-FP-ATPCS-NEXT:    bne .LBB7_1
; CHECK-FP-ATPCS-NEXT:  @ %bb.2: @ %entry
; CHECK-FP-ATPCS-NEXT:    adds r4, r6, #7
; CHECK-FP-ATPCS-NEXT:    adds r4, #1
; CHECK-FP-ATPCS-NEXT:    movs r2, #0
; CHECK-FP-ATPCS-NEXT:    mov r0, r4
; CHECK-FP-ATPCS-NEXT:    mov r1, r5
; CHECK-FP-ATPCS-NEXT:    mov r3, r2
; CHECK-FP-ATPCS-NEXT:    bl f
; CHECK-FP-ATPCS-NEXT:    add sp, #508
; CHECK-FP-ATPCS-NEXT:    add sp, #4
; CHECK-FP-ATPCS-NEXT:    mov r5, r0
; CHECK-FP-ATPCS-NEXT:    adds r1, r4, #4
; CHECK-FP-ATPCS-NEXT:    mov r2, r4
; CHECK-FP-ATPCS-NEXT:    adds r2, #8
; CHECK-FP-ATPCS-NEXT:    mov r0, r4
; CHECK-FP-ATPCS-NEXT:    bl h
; CHECK-FP-ATPCS-NEXT:    adds r0, r0, r5
; CHECK-FP-ATPCS-NEXT:    add sp, #24
; CHECK-FP-ATPCS-NEXT:    pop {r4, r5, r6, r7}
; CHECK-FP-ATPCS-NEXT:    pop {r1}
; CHECK-FP-ATPCS-NEXT:    add sp, #12
; CHECK-FP-ATPCS-NEXT:    bx r1
; CHECK-FP-ATPCS-NEXT:    .p2align 2
; CHECK-FP-ATPCS-NEXT:  @ %bb.3:
; CHECK-FP-ATPCS-NEXT:  .LCPI7_0:
; CHECK-FP-ATPCS-NEXT:    .long s
; CHECK-FP-ATPCS-NEXT:  .LCPI7_1:
; CHECK-FP-ATPCS-NEXT:    .long 512 @ 0x200
;
; CHECK-FP-AAPCS-LABEL: test_varargs_moving_sp:
; CHECK-FP-AAPCS:       @ %bb.0: @ %entry
; CHECK-FP-AAPCS-NEXT:    .pad #12
; CHECK-FP-AAPCS-NEXT:    sub sp, #12
; CHECK-FP-AAPCS-NEXT:    .save {lr}
; CHECK-FP-AAPCS-NEXT:    push {lr}
; CHECK-FP-AAPCS-NEXT:    mov lr, r11
; CHECK-FP-AAPCS-NEXT:    .save {r11}
; CHECK-FP-AAPCS-NEXT:    push {lr}
; CHECK-FP-AAPCS-NEXT:    .setfp r11, sp
; CHECK-FP-AAPCS-NEXT:    mov r11, sp
; CHECK-FP-AAPCS-NEXT:    .save {r4, r5, r6, r7}
; CHECK-FP-AAPCS-NEXT:    push {r4, r5, r6, r7}
; CHECK-FP-AAPCS-NEXT:    .pad #20
; CHECK-FP-AAPCS-NEXT:    sub sp, #20
; CHECK-FP-AAPCS-NEXT:    mov r6, sp
; CHECK-FP-AAPCS-NEXT:    mov r4, r0
; CHECK-FP-AAPCS-NEXT:    mov r0, r11
; CHECK-FP-AAPCS-NEXT:    mov r5, r0
; CHECK-FP-AAPCS-NEXT:    adds r5, #8
; CHECK-FP-AAPCS-NEXT:    stm r5!, {r1, r2, r3}
; CHECK-FP-AAPCS-NEXT:    adds r0, #8
; CHECK-FP-AAPCS-NEXT:    str r0, [r6]
; CHECK-FP-AAPCS-NEXT:    sub sp, #508
; CHECK-FP-AAPCS-NEXT:    sub sp, #4
; CHECK-FP-AAPCS-NEXT:    ldr r0, .LCPI7_0
; CHECK-FP-AAPCS-NEXT:    mov r1, sp
; CHECK-FP-AAPCS-NEXT:    ldr r2, .LCPI7_1
; CHECK-FP-AAPCS-NEXT:  .LBB7_1: @ %entry
; CHECK-FP-AAPCS-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-FP-AAPCS-NEXT:    ldr r3, [r0]
; CHECK-FP-AAPCS-NEXT:    adds r0, #4
; CHECK-FP-AAPCS-NEXT:    str r3, [r1]
; CHECK-FP-AAPCS-NEXT:    adds r1, #4
; CHECK-FP-AAPCS-NEXT:    subs r2, #4
; CHECK-FP-AAPCS-NEXT:    bne .LBB7_1
; CHECK-FP-AAPCS-NEXT:  @ %bb.2: @ %entry
; CHECK-FP-AAPCS-NEXT:    adds r5, r6, #4
; CHECK-FP-AAPCS-NEXT:    movs r2, #0
; CHECK-FP-AAPCS-NEXT:    mov r0, r5
; CHECK-FP-AAPCS-NEXT:    mov r1, r4
; CHECK-FP-AAPCS-NEXT:    mov r3, r2
; CHECK-FP-AAPCS-NEXT:    bl f
; CHECK-FP-AAPCS-NEXT:    add sp, #508
; CHECK-FP-AAPCS-NEXT:    add sp, #4
; CHECK-FP-AAPCS-NEXT:    mov r4, r0
; CHECK-FP-AAPCS-NEXT:    adds r1, r5, #4
; CHECK-FP-AAPCS-NEXT:    mov r2, r5
; CHECK-FP-AAPCS-NEXT:    adds r2, #8
; CHECK-FP-AAPCS-NEXT:    mov r0, r5
; CHECK-FP-AAPCS-NEXT:    bl h
; CHECK-FP-AAPCS-NEXT:    adds r0, r0, r4
; CHECK-FP-AAPCS-NEXT:    add sp, #20
; CHECK-FP-AAPCS-NEXT:    pop {r4, r5, r6, r7}
; CHECK-FP-AAPCS-NEXT:    pop {r1}
; CHECK-FP-AAPCS-NEXT:    mov r11, r1
; CHECK-FP-AAPCS-NEXT:    pop {r1}
; CHECK-FP-AAPCS-NEXT:    add sp, #12
; CHECK-FP-AAPCS-NEXT:    bx r1
; CHECK-FP-AAPCS-NEXT:    .p2align 2
; CHECK-FP-AAPCS-NEXT:  @ %bb.3:
; CHECK-FP-AAPCS-NEXT:  .LCPI7_0:
; CHECK-FP-AAPCS-NEXT:    .long s
; CHECK-FP-AAPCS-NEXT:  .LCPI7_1:
; CHECK-FP-AAPCS-NEXT:    .long 512 @ 0x200
entry:
  %v = alloca [4 x i32], align 4
  %ap = alloca %struct.__va_list, align 4
  call void @llvm.va_start(ptr nonnull %ap)
  %call = call i32 @f(ptr nonnull %v, i32 %a, i32 0, i32 0, ptr byval(%struct.S) nonnull align 4 @s)
  %add.ptr = getelementptr inbounds [4 x i32], ptr %v, i32 0, i32 1
  %add.ptr5 = getelementptr inbounds [4 x i32], ptr %v, i32 0, i32 2
  %call6 = call i32 @h(ptr nonnull %v, ptr nonnull %add.ptr, ptr nonnull %add.ptr5)
  %add = add nsw i32 %call6, %call
  ret i32 %add
}
; CHECK-LABEL: test_varargs_moving_sp
; Three incoming register varargs
; CHECK:       sub sp, #12
; 16 bytes callee-saves without FP
; CHECK-NOFP: push {r4, r5, r6, lr}
; 24 bytes callee-saves with FP
; CHECK-FP-ATPCS: push {r4, r5, r6, r7, lr}
; CHECK-FP-AAPCS: push {lr}
; CHECK-FP-AAPCS: mov lr, r11
; CHECK-FP-AAPCS: push {lr}
; CHECK-FP-AAPCS: push {r4, r5, r6, r7}
; Locals area
; CHECK-NOFP:       sub sp, #20
; CHECK-FP-ATPCS:   sub sp, #24
; CHECK-FP-AAPCS:   sub sp, #20
; Incoming varargs stored via BP if FP is not present (36 = 20 + 16)
; CHECK-NOFP:      mov r0, r6
; CHECK-NOFP-NEXT: adds r0, #36
; CHECK-NOFP-NEXT: stm r0!, {r1, r2, r3}
; Incoming varargs stored via FP otherwise
; CHECK-FP-ATPCS:      mov r0, r7
; CHECK-FP-ATPCS-NEXT: adds r0, #8
; CHECK-FP-ATPCS-NEXT: stm r0!, {r1, r2, r3}
; CHECK-FP-AAPCS:      mov r0, r11
; CHECK-FP-AAPCS-NEXT: mov r5, r0
; CHECK-FP-AAPCS-NEXT: adds r5, #8
; CHECK-FP-AAPCS-NEXT: stm r5!, {r1, r2, r3}

; struct S { int x[128]; } s;
; int test(S a, int b) {
;   return i(b);
; }
define dso_local i32 @test_args_large_offset(ptr byval(%struct.S) align 4 %0, i32 %1) local_unnamed_addr {
; CHECK-NOFP-LABEL: test_args_large_offset:
; CHECK-NOFP:       @ %bb.0:
; CHECK-NOFP-NEXT:    .pad #16
; CHECK-NOFP-NEXT:    sub sp, #16
; CHECK-NOFP-NEXT:    .save {r7, lr}
; CHECK-NOFP-NEXT:    push {r7, lr}
; CHECK-NOFP-NEXT:    add r7, sp, #8
; CHECK-NOFP-NEXT:    stm r7!, {r0, r1, r2, r3}
; CHECK-NOFP-NEXT:    ldr r0, [sp, #520]
; CHECK-NOFP-NEXT:    bl i
; CHECK-NOFP-NEXT:    pop {r7}
; CHECK-NOFP-NEXT:    pop {r1}
; CHECK-NOFP-NEXT:    add sp, #16
; CHECK-NOFP-NEXT:    bx r1
;
; CHECK-FP-ATPCS-LABEL: test_args_large_offset:
; CHECK-FP-ATPCS:       @ %bb.0:
; CHECK-FP-ATPCS-NEXT:    .pad #16
; CHECK-FP-ATPCS-NEXT:    sub sp, #16
; CHECK-FP-ATPCS-NEXT:    .save {r4, r5, r7, lr}
; CHECK-FP-ATPCS-NEXT:    push {r4, r5, r7, lr}
; CHECK-FP-ATPCS-NEXT:    .setfp r7, sp, #8
; CHECK-FP-ATPCS-NEXT:    add r7, sp, #8
; CHECK-FP-ATPCS-NEXT:    mov r4, r7
; CHECK-FP-ATPCS-NEXT:    adds r4, #8
; CHECK-FP-ATPCS-NEXT:    stm r4!, {r0, r1, r2, r3}
; CHECK-FP-ATPCS-NEXT:    ldr r0, .LCPI8_0
; CHECK-FP-ATPCS-NEXT:    ldr r0, [r0, r7]
; CHECK-FP-ATPCS-NEXT:    bl i
; CHECK-FP-ATPCS-NEXT:    pop {r4, r5, r7}
; CHECK-FP-ATPCS-NEXT:    pop {r1}
; CHECK-FP-ATPCS-NEXT:    add sp, #16
; CHECK-FP-ATPCS-NEXT:    bx r1
; CHECK-FP-ATPCS-NEXT:    .p2align 2
; CHECK-FP-ATPCS-NEXT:  @ %bb.1:
; CHECK-FP-ATPCS-NEXT:  .LCPI8_0:
; CHECK-FP-ATPCS-NEXT:    .long 520 @ 0x208
;
; CHECK-FP-AAPCS-LABEL: test_args_large_offset:
; CHECK-FP-AAPCS:       @ %bb.0:
; CHECK-FP-AAPCS-NEXT:    .pad #16
; CHECK-FP-AAPCS-NEXT:    sub sp, #16
; CHECK-FP-AAPCS-NEXT:    .save {lr}
; CHECK-FP-AAPCS-NEXT:    push {lr}
; CHECK-FP-AAPCS-NEXT:    mov lr, r11
; CHECK-FP-AAPCS-NEXT:    .save {r11}
; CHECK-FP-AAPCS-NEXT:    push {lr}
; CHECK-FP-AAPCS-NEXT:    .setfp r11, sp
; CHECK-FP-AAPCS-NEXT:    mov r11, sp
; CHECK-FP-AAPCS-NEXT:    .save {r4, r5}
; CHECK-FP-AAPCS-NEXT:    push {r4, r5}
; CHECK-FP-AAPCS-NEXT:    mov r4, r11
; CHECK-FP-AAPCS-NEXT:    str r0, [r4, #8]
; CHECK-FP-AAPCS-NEXT:    mov r0, r11
; CHECK-FP-AAPCS-NEXT:    adds r0, #12
; CHECK-FP-AAPCS-NEXT:    stm r0!, {r1, r2, r3}
; CHECK-FP-AAPCS-NEXT:    ldr r0, .LCPI8_0
; CHECK-FP-AAPCS-NEXT:    add r0, r11
; CHECK-FP-AAPCS-NEXT:    ldr r0, [r0]
; CHECK-FP-AAPCS-NEXT:    bl i
; CHECK-FP-AAPCS-NEXT:    pop {r4, r5}
; CHECK-FP-AAPCS-NEXT:    pop {r1}
; CHECK-FP-AAPCS-NEXT:    mov r11, r1
; CHECK-FP-AAPCS-NEXT:    pop {r1}
; CHECK-FP-AAPCS-NEXT:    add sp, #16
; CHECK-FP-AAPCS-NEXT:    bx r1
; CHECK-FP-AAPCS-NEXT:    .p2align 2
; CHECK-FP-AAPCS-NEXT:  @ %bb.1:
; CHECK-FP-AAPCS-NEXT:  .LCPI8_0:
; CHECK-FP-AAPCS-NEXT:    .long 520 @ 0x208
  %3 = alloca i32, align 4
  store i32 %1, ptr %3, align 4
  %4 = load i32, ptr %3, align 4
  %5 = call i32 @i(i32 %4)
  ret i32 %5
}
; CHECK-LABEL: test_args_large_offset
; Without FP: Access to large offset is made using SP
; CHECK-NOFP:     ldr r0, [sp, #520]
; With FP: Access to large offset is made through a const pool using FP
; CHECK-FP:       ldr r0, .LCPI0_0
; CHECK-FP-ATPCS: ldr r0, [r0, r7]
; CHECK-FP-AAPCS: add r0, r11
; CHECK-FP-AAPCS: ldr r0, [r0]
; CHECK: bl i

;
; Access to locals
;

; Usual case, access via SP.
; int test_local(int n) {
;   int v[4];
;   int x, y, z;
;   h(&x, &y, &z);
;   return g(v, x, y, z, 0, 0);
; }
define dso_local i32 @test_local(i32 %n) local_unnamed_addr  {
; CHECK-NOFP-LABEL: test_local:
; CHECK-NOFP:       @ %bb.0: @ %entry
; CHECK-NOFP-NEXT:    .save {r7, lr}
; CHECK-NOFP-NEXT:    push {r7, lr}
; CHECK-NOFP-NEXT:    .pad #40
; CHECK-NOFP-NEXT:    sub sp, #40
; CHECK-NOFP-NEXT:    add r0, sp, #20
; CHECK-NOFP-NEXT:    add r1, sp, #16
; CHECK-NOFP-NEXT:    add r2, sp, #12
; CHECK-NOFP-NEXT:    bl h
; CHECK-NOFP-NEXT:    ldr r1, [sp, #20]
; CHECK-NOFP-NEXT:    ldr r2, [sp, #16]
; CHECK-NOFP-NEXT:    ldr r3, [sp, #12]
; CHECK-NOFP-NEXT:    movs r0, #0
; CHECK-NOFP-NEXT:    str r0, [sp]
; CHECK-NOFP-NEXT:    str r0, [sp, #4]
; CHECK-NOFP-NEXT:    add r0, sp, #24
; CHECK-NOFP-NEXT:    bl g
; CHECK-NOFP-NEXT:    add sp, #40
; CHECK-NOFP-NEXT:    pop {r7, pc}
;
; CHECK-FP-ATPCS-LABEL: test_local:
; CHECK-FP-ATPCS:       @ %bb.0: @ %entry
; CHECK-FP-ATPCS-NEXT:    .save {r7, lr}
; CHECK-FP-ATPCS-NEXT:    push {r7, lr}
; CHECK-FP-ATPCS-NEXT:    .setfp r7, sp
; CHECK-FP-ATPCS-NEXT:    add r7, sp, #0
; CHECK-FP-ATPCS-NEXT:    .pad #40
; CHECK-FP-ATPCS-NEXT:    sub sp, #40
; CHECK-FP-ATPCS-NEXT:    add r0, sp, #20
; CHECK-FP-ATPCS-NEXT:    add r1, sp, #16
; CHECK-FP-ATPCS-NEXT:    add r2, sp, #12
; CHECK-FP-ATPCS-NEXT:    bl h
; CHECK-FP-ATPCS-NEXT:    ldr r1, [sp, #20]
; CHECK-FP-ATPCS-NEXT:    ldr r2, [sp, #16]
; CHECK-FP-ATPCS-NEXT:    ldr r3, [sp, #12]
; CHECK-FP-ATPCS-NEXT:    movs r0, #0
; CHECK-FP-ATPCS-NEXT:    str r0, [sp]
; CHECK-FP-ATPCS-NEXT:    str r0, [sp, #4]
; CHECK-FP-ATPCS-NEXT:    add r0, sp, #24
; CHECK-FP-ATPCS-NEXT:    bl g
; CHECK-FP-ATPCS-NEXT:    add sp, #40
; CHECK-FP-ATPCS-NEXT:    pop {r7, pc}
;
; CHECK-FP-AAPCS-LABEL: test_local:
; CHECK-FP-AAPCS:       @ %bb.0: @ %entry
; CHECK-FP-AAPCS-NEXT:    .save {lr}
; CHECK-FP-AAPCS-NEXT:    push {lr}
; CHECK-FP-AAPCS-NEXT:    mov lr, r11
; CHECK-FP-AAPCS-NEXT:    .save {r11}
; CHECK-FP-AAPCS-NEXT:    push {lr}
; CHECK-FP-AAPCS-NEXT:    .setfp r11, sp
; CHECK-FP-AAPCS-NEXT:    mov r11, sp
; CHECK-FP-AAPCS-NEXT:    .pad #40
; CHECK-FP-AAPCS-NEXT:    sub sp, #40
; CHECK-FP-AAPCS-NEXT:    add r0, sp, #20
; CHECK-FP-AAPCS-NEXT:    add r1, sp, #16
; CHECK-FP-AAPCS-NEXT:    add r2, sp, #12
; CHECK-FP-AAPCS-NEXT:    bl h
; CHECK-FP-AAPCS-NEXT:    ldr r1, [sp, #20]
; CHECK-FP-AAPCS-NEXT:    ldr r2, [sp, #16]
; CHECK-FP-AAPCS-NEXT:    ldr r3, [sp, #12]
; CHECK-FP-AAPCS-NEXT:    movs r0, #0
; CHECK-FP-AAPCS-NEXT:    str r0, [sp]
; CHECK-FP-AAPCS-NEXT:    str r0, [sp, #4]
; CHECK-FP-AAPCS-NEXT:    add r0, sp, #24
; CHECK-FP-AAPCS-NEXT:    bl g
; CHECK-FP-AAPCS-NEXT:    add sp, #40
; CHECK-FP-AAPCS-NEXT:    pop {r1}
; CHECK-FP-AAPCS-NEXT:    mov r11, r1
; CHECK-FP-AAPCS-NEXT:    pop {pc}
entry:
  %v = alloca [4 x i32], align 4
  %x = alloca i32, align 4
  %y = alloca i32, align 4
  %z = alloca i32, align 4
  %call = call i32 @h(ptr nonnull %x, ptr nonnull %y, ptr nonnull %z)
  %0 = load i32, ptr %x, align 4
  %1 = load i32, ptr %y, align 4
  %2 = load i32, ptr %z, align 4
  %call1 = call i32 @g(ptr nonnull %v, i32 %0, i32 %1, i32 %2, i32 0, i32 0)
  ret i32 %call1
}
; CHECK-LABEL: test_local
; Arguments to `h` relative to SP
; CHECK:       add r0, sp, #20
; CHECK-NEXT:  add r1, sp, #16
; CHECK-NEXT:  add r2, sp, #12
; CHECK-NEXT:  bl  h
; Load `x`, `y`, and `z` via SP
; CHECK:       ldr r1, [sp, #20]
; CHECK-NEXT:  ldr r2, [sp, #16]
; CHECK-NEXT:  ldr r3, [sp, #12]
; CHECK:       bl  g

; Re-aligned stack, access via SP.
; int test_local_realign(int n) {
;   __attribute__((aligned(16))) int v[4];
;   int x, y, z;
;   h(&x, &y, &z);
;   return g(v, x, y, z, 0, 0);
; }
define dso_local i32 @test_local_realign(i32 %n) local_unnamed_addr  {
; CHECK-ATPCS-LABEL: test_local_realign:
; CHECK-ATPCS:       @ %bb.0: @ %entry
; CHECK-ATPCS-NEXT:    .save {r4, r6, r7, lr}
; CHECK-ATPCS-NEXT:    push {r4, r6, r7, lr}
; CHECK-ATPCS-NEXT:    .setfp r7, sp, #8
; CHECK-ATPCS-NEXT:    add r7, sp, #8
; CHECK-ATPCS-NEXT:    .pad #48
; CHECK-ATPCS-NEXT:    sub sp, #48
; CHECK-ATPCS-NEXT:    mov r4, sp
; CHECK-ATPCS-NEXT:    lsrs r4, r4, #4
; CHECK-ATPCS-NEXT:    lsls r4, r4, #4
; CHECK-ATPCS-NEXT:    mov sp, r4
; CHECK-ATPCS-NEXT:    add r0, sp, #28
; CHECK-ATPCS-NEXT:    add r1, sp, #24
; CHECK-ATPCS-NEXT:    add r2, sp, #20
; CHECK-ATPCS-NEXT:    bl h
; CHECK-ATPCS-NEXT:    ldr r1, [sp, #28]
; CHECK-ATPCS-NEXT:    ldr r2, [sp, #24]
; CHECK-ATPCS-NEXT:    ldr r3, [sp, #20]
; CHECK-ATPCS-NEXT:    movs r0, #0
; CHECK-ATPCS-NEXT:    str r0, [sp]
; CHECK-ATPCS-NEXT:    str r0, [sp, #4]
; CHECK-ATPCS-NEXT:    add r0, sp, #32
; CHECK-ATPCS-NEXT:    bl g
; CHECK-ATPCS-NEXT:    subs r6, r7, #7
; CHECK-ATPCS-NEXT:    subs r6, #1
; CHECK-ATPCS-NEXT:    mov sp, r6
; CHECK-ATPCS-NEXT:    pop {r4, r6, r7, pc}
;
; CHECK-FP-ATPCS-LABEL: test_local_realign:
; CHECK-FP-ATPCS:       @ %bb.0: @ %entry
; CHECK-FP-ATPCS-NEXT:    .save {r4, r6, r7, lr}
; CHECK-FP-ATPCS-NEXT:    push {r4, r6, r7, lr}
; CHECK-FP-ATPCS-NEXT:    .setfp r7, sp, #8
; CHECK-FP-ATPCS-NEXT:    add r7, sp, #8
; CHECK-FP-ATPCS-NEXT:    .pad #48
; CHECK-FP-ATPCS-NEXT:    sub sp, #48
; CHECK-FP-ATPCS-NEXT:    mov r4, sp
; CHECK-FP-ATPCS-NEXT:    lsrs r4, r4, #4
; CHECK-FP-ATPCS-NEXT:    lsls r4, r4, #4
; CHECK-FP-ATPCS-NEXT:    mov sp, r4
; CHECK-FP-ATPCS-NEXT:    add r0, sp, #28
; CHECK-FP-ATPCS-NEXT:    add r1, sp, #24
; CHECK-FP-ATPCS-NEXT:    add r2, sp, #20
; CHECK-FP-ATPCS-NEXT:    bl h
; CHECK-FP-ATPCS-NEXT:    ldr r1, [sp, #28]
; CHECK-FP-ATPCS-NEXT:    ldr r2, [sp, #24]
; CHECK-FP-ATPCS-NEXT:    ldr r3, [sp, #20]
; CHECK-FP-ATPCS-NEXT:    movs r0, #0
; CHECK-FP-ATPCS-NEXT:    str r0, [sp]
; CHECK-FP-ATPCS-NEXT:    str r0, [sp, #4]
; CHECK-FP-ATPCS-NEXT:    add r0, sp, #32
; CHECK-FP-ATPCS-NEXT:    bl g
; CHECK-FP-ATPCS-NEXT:    subs r6, r7, #7
; CHECK-FP-ATPCS-NEXT:    subs r6, #1
; CHECK-FP-ATPCS-NEXT:    mov sp, r6
; CHECK-FP-ATPCS-NEXT:    pop {r4, r6, r7, pc}
;
; CHECK-AAPCS-LABEL: test_local_realign:
; CHECK-AAPCS:       @ %bb.0: @ %entry
; CHECK-AAPCS-NEXT:    .save {lr}
; CHECK-AAPCS-NEXT:    push {lr}
; CHECK-AAPCS-NEXT:    mov lr, r11
; CHECK-AAPCS-NEXT:    .save {r11}
; CHECK-AAPCS-NEXT:    push {lr}
; CHECK-AAPCS-NEXT:    .setfp r11, sp
; CHECK-AAPCS-NEXT:    mov r11, sp
; CHECK-AAPCS-NEXT:    .save {r4, r7}
; CHECK-AAPCS-NEXT:    push {r4, r7}
; CHECK-AAPCS-NEXT:    .pad #48
; CHECK-AAPCS-NEXT:    sub sp, #48
; CHECK-AAPCS-NEXT:    mov r4, sp
; CHECK-AAPCS-NEXT:    lsrs r4, r4, #4
; CHECK-AAPCS-NEXT:    lsls r4, r4, #4
; CHECK-AAPCS-NEXT:    mov sp, r4
; CHECK-AAPCS-NEXT:    add r0, sp, #28
; CHECK-AAPCS-NEXT:    add r1, sp, #24
; CHECK-AAPCS-NEXT:    add r2, sp, #20
; CHECK-AAPCS-NEXT:    bl h
; CHECK-AAPCS-NEXT:    ldr r1, [sp, #28]
; CHECK-AAPCS-NEXT:    ldr r2, [sp, #24]
; CHECK-AAPCS-NEXT:    ldr r3, [sp, #20]
; CHECK-AAPCS-NEXT:    movs r0, #0
; CHECK-AAPCS-NEXT:    str r0, [sp]
; CHECK-AAPCS-NEXT:    str r0, [sp, #4]
; CHECK-AAPCS-NEXT:    add r0, sp, #32
; CHECK-AAPCS-NEXT:    bl g
; CHECK-AAPCS-NEXT:    mov r7, r11
; CHECK-AAPCS-NEXT:    subs r7, #8
; CHECK-AAPCS-NEXT:    mov sp, r7
; CHECK-AAPCS-NEXT:    pop {r4, r7}
; CHECK-AAPCS-NEXT:    pop {r1}
; CHECK-AAPCS-NEXT:    mov r11, r1
; CHECK-AAPCS-NEXT:    pop {pc}
;
; CHECK-FP-AAPCS-LABEL: test_local_realign:
; CHECK-FP-AAPCS:       @ %bb.0: @ %entry
; CHECK-FP-AAPCS-NEXT:    .save {lr}
; CHECK-FP-AAPCS-NEXT:    push {lr}
; CHECK-FP-AAPCS-NEXT:    mov lr, r11
; CHECK-FP-AAPCS-NEXT:    .save {r11}
; CHECK-FP-AAPCS-NEXT:    push {lr}
; CHECK-FP-AAPCS-NEXT:    .setfp r11, sp
; CHECK-FP-AAPCS-NEXT:    mov r11, sp
; CHECK-FP-AAPCS-NEXT:    .save {r4, r7}
; CHECK-FP-AAPCS-NEXT:    push {r4, r7}
; CHECK-FP-AAPCS-NEXT:    .pad #48
; CHECK-FP-AAPCS-NEXT:    sub sp, #48
; CHECK-FP-AAPCS-NEXT:    mov r4, sp
; CHECK-FP-AAPCS-NEXT:    lsrs r4, r4, #4
; CHECK-FP-AAPCS-NEXT:    lsls r4, r4, #4
; CHECK-FP-AAPCS-NEXT:    mov sp, r4
; CHECK-FP-AAPCS-NEXT:    add r0, sp, #28
; CHECK-FP-AAPCS-NEXT:    add r1, sp, #24
; CHECK-FP-AAPCS-NEXT:    add r2, sp, #20
; CHECK-FP-AAPCS-NEXT:    bl h
; CHECK-FP-AAPCS-NEXT:    ldr r1, [sp, #28]
; CHECK-FP-AAPCS-NEXT:    ldr r2, [sp, #24]
; CHECK-FP-AAPCS-NEXT:    ldr r3, [sp, #20]
; CHECK-FP-AAPCS-NEXT:    movs r0, #0
; CHECK-FP-AAPCS-NEXT:    str r0, [sp]
; CHECK-FP-AAPCS-NEXT:    str r0, [sp, #4]
; CHECK-FP-AAPCS-NEXT:    add r0, sp, #32
; CHECK-FP-AAPCS-NEXT:    bl g
; CHECK-FP-AAPCS-NEXT:    mov r7, r11
; CHECK-FP-AAPCS-NEXT:    subs r7, #8
; CHECK-FP-AAPCS-NEXT:    mov sp, r7
; CHECK-FP-AAPCS-NEXT:    pop {r4, r7}
; CHECK-FP-AAPCS-NEXT:    pop {r1}
; CHECK-FP-AAPCS-NEXT:    mov r11, r1
; CHECK-FP-AAPCS-NEXT:    pop {pc}
entry:
  %v = alloca [4 x i32], align 16
  %x = alloca i32, align 4
  %y = alloca i32, align 4
  %z = alloca i32, align 4
  %call = call i32 @h(ptr nonnull %x, ptr nonnull %y, ptr nonnull %z)
  %0 = load i32, ptr %x, align 4
  %1 = load i32, ptr %y, align 4
  %2 = load i32, ptr %z, align 4
  %call1 = call i32 @g(ptr nonnull %v, i32 %0, i32 %1, i32 %2, i32 0, i32 0)
  ret i32 %call1
}
; CHECK-LABEL: test_local_realign
; Setup frame pointer
; CHECK-ATPCS: add r7, sp, #8
; CHECK-AAPCS: mov r11, sp
; Re-align stack
; CHECK:       mov r4, sp
; CHECK-NEXT:  lsrs r4, r4, #4
; CHECK-NEXT:  lsls r4, r4, #4
; CHECK-NEXT:  mov  sp, r4
; Arguments to `h` computed relative to SP
; CHECK:       add r0, sp, #28
; CHECK-NEXT:  add r1, sp, #24
; CHECK-NEXT:  add r2, sp, #20
; CHECK-NEXT:  bl  h
; Load `x`, `y`, and `z` via SP for passing to `g`
; CHECK:       ldr r1, [sp, #28]
; CHECK-NEXT:  ldr r2, [sp, #24]
; CHECK-NEXT:  ldr r3, [sp, #20]
; CHECK:       bl  g

; VLAs, access via BP.
; int test_local_vla(int n) {
;   int v[n];
;   int x, y, z;
;   h(&x, &y, &z);
;   return g(v, x, y, z, 0, 0);
; }
define dso_local i32 @test_local_vla(i32 %n) local_unnamed_addr  {
; CHECK-ATPCS-LABEL: test_local_vla:
; CHECK-ATPCS:       @ %bb.0: @ %entry
; CHECK-ATPCS-NEXT:    .save {r4, r5, r6, r7, lr}
; CHECK-ATPCS-NEXT:    push {r4, r5, r6, r7, lr}
; CHECK-ATPCS-NEXT:    .setfp r7, sp, #12
; CHECK-ATPCS-NEXT:    add r7, sp, #12
; CHECK-ATPCS-NEXT:    .pad #12
; CHECK-ATPCS-NEXT:    sub sp, #12
; CHECK-ATPCS-NEXT:    mov r6, sp
; CHECK-ATPCS-NEXT:    mov r5, r6
; CHECK-ATPCS-NEXT:    lsls r0, r0, #2
; CHECK-ATPCS-NEXT:    adds r0, r0, #7
; CHECK-ATPCS-NEXT:    movs r1, #7
; CHECK-ATPCS-NEXT:    bics r0, r1
; CHECK-ATPCS-NEXT:    mov r1, sp
; CHECK-ATPCS-NEXT:    subs r4, r1, r0
; CHECK-ATPCS-NEXT:    mov sp, r4
; CHECK-ATPCS-NEXT:    adds r0, r6, #7
; CHECK-ATPCS-NEXT:    adds r0, #1
; CHECK-ATPCS-NEXT:    adds r1, r6, #4
; CHECK-ATPCS-NEXT:    mov r2, r6
; CHECK-ATPCS-NEXT:    bl h
; CHECK-ATPCS-NEXT:    ldr r3, [r5]
; CHECK-ATPCS-NEXT:    ldr r2, [r5, #4]
; CHECK-ATPCS-NEXT:    ldr r1, [r5, #8]
; CHECK-ATPCS-NEXT:    sub sp, #8
; CHECK-ATPCS-NEXT:    movs r0, #0
; CHECK-ATPCS-NEXT:    str r0, [sp]
; CHECK-ATPCS-NEXT:    str r0, [sp, #4]
; CHECK-ATPCS-NEXT:    mov r0, r4
; CHECK-ATPCS-NEXT:    bl g
; CHECK-ATPCS-NEXT:    add sp, #8
; CHECK-ATPCS-NEXT:    subs r6, r7, #7
; CHECK-ATPCS-NEXT:    subs r6, #5
; CHECK-ATPCS-NEXT:    mov sp, r6
; CHECK-ATPCS-NEXT:    pop {r4, r5, r6, r7, pc}
;
; CHECK-FP-ATPCS-LABEL: test_local_vla:
; CHECK-FP-ATPCS:       @ %bb.0: @ %entry
; CHECK-FP-ATPCS-NEXT:    .save {r4, r5, r6, r7, lr}
; CHECK-FP-ATPCS-NEXT:    push {r4, r5, r6, r7, lr}
; CHECK-FP-ATPCS-NEXT:    .setfp r7, sp, #12
; CHECK-FP-ATPCS-NEXT:    add r7, sp, #12
; CHECK-FP-ATPCS-NEXT:    .pad #12
; CHECK-FP-ATPCS-NEXT:    sub sp, #12
; CHECK-FP-ATPCS-NEXT:    mov r6, sp
; CHECK-FP-ATPCS-NEXT:    mov r5, r6
; CHECK-FP-ATPCS-NEXT:    lsls r0, r0, #2
; CHECK-FP-ATPCS-NEXT:    adds r0, r0, #7
; CHECK-FP-ATPCS-NEXT:    movs r1, #7
; CHECK-FP-ATPCS-NEXT:    bics r0, r1
; CHECK-FP-ATPCS-NEXT:    mov r1, sp
; CHECK-FP-ATPCS-NEXT:    subs r4, r1, r0
; CHECK-FP-ATPCS-NEXT:    mov sp, r4
; CHECK-FP-ATPCS-NEXT:    adds r0, r6, #7
; CHECK-FP-ATPCS-NEXT:    adds r0, #1
; CHECK-FP-ATPCS-NEXT:    adds r1, r6, #4
; CHECK-FP-ATPCS-NEXT:    mov r2, r6
; CHECK-FP-ATPCS-NEXT:    bl h
; CHECK-FP-ATPCS-NEXT:    ldr r3, [r5]
; CHECK-FP-ATPCS-NEXT:    ldr r2, [r5, #4]
; CHECK-FP-ATPCS-NEXT:    ldr r1, [r5, #8]
; CHECK-FP-ATPCS-NEXT:    sub sp, #8
; CHECK-FP-ATPCS-NEXT:    movs r0, #0
; CHECK-FP-ATPCS-NEXT:    str r0, [sp]
; CHECK-FP-ATPCS-NEXT:    str r0, [sp, #4]
; CHECK-FP-ATPCS-NEXT:    mov r0, r4
; CHECK-FP-ATPCS-NEXT:    bl g
; CHECK-FP-ATPCS-NEXT:    add sp, #8
; CHECK-FP-ATPCS-NEXT:    subs r6, r7, #7
; CHECK-FP-ATPCS-NEXT:    subs r6, #5
; CHECK-FP-ATPCS-NEXT:    mov sp, r6
; CHECK-FP-ATPCS-NEXT:    pop {r4, r5, r6, r7, pc}
;
; CHECK-AAPCS-LABEL: test_local_vla:
; CHECK-AAPCS:       @ %bb.0: @ %entry
; CHECK-AAPCS-NEXT:    .save {lr}
; CHECK-AAPCS-NEXT:    push {lr}
; CHECK-AAPCS-NEXT:    mov lr, r11
; CHECK-AAPCS-NEXT:    .save {r11}
; CHECK-AAPCS-NEXT:    push {lr}
; CHECK-AAPCS-NEXT:    .setfp r11, sp
; CHECK-AAPCS-NEXT:    mov r11, sp
; CHECK-AAPCS-NEXT:    .save {r4, r5, r6, r7}
; CHECK-AAPCS-NEXT:    push {r4, r5, r6, r7}
; CHECK-AAPCS-NEXT:    .pad #16
; CHECK-AAPCS-NEXT:    sub sp, #16
; CHECK-AAPCS-NEXT:    mov r6, sp
; CHECK-AAPCS-NEXT:    adds r5, r6, #4
; CHECK-AAPCS-NEXT:    lsls r0, r0, #2
; CHECK-AAPCS-NEXT:    adds r0, r0, #7
; CHECK-AAPCS-NEXT:    movs r1, #7
; CHECK-AAPCS-NEXT:    bics r0, r1
; CHECK-AAPCS-NEXT:    mov r1, sp
; CHECK-AAPCS-NEXT:    subs r4, r1, r0
; CHECK-AAPCS-NEXT:    mov sp, r4
; CHECK-AAPCS-NEXT:    adds r0, r6, #7
; CHECK-AAPCS-NEXT:    adds r0, #5
; CHECK-AAPCS-NEXT:    adds r1, r6, #7
; CHECK-AAPCS-NEXT:    adds r1, #1
; CHECK-AAPCS-NEXT:    adds r2, r6, #4
; CHECK-AAPCS-NEXT:    bl h
; CHECK-AAPCS-NEXT:    ldr r3, [r5]
; CHECK-AAPCS-NEXT:    ldr r2, [r5, #4]
; CHECK-AAPCS-NEXT:    ldr r1, [r5, #8]
; CHECK-AAPCS-NEXT:    sub sp, #8
; CHECK-AAPCS-NEXT:    movs r0, #0
; CHECK-AAPCS-NEXT:    str r0, [sp]
; CHECK-AAPCS-NEXT:    str r0, [sp, #4]
; CHECK-AAPCS-NEXT:    mov r0, r4
; CHECK-AAPCS-NEXT:    bl g
; CHECK-AAPCS-NEXT:    add sp, #8
; CHECK-AAPCS-NEXT:    mov r7, r11
; CHECK-AAPCS-NEXT:    subs r7, #16
; CHECK-AAPCS-NEXT:    mov sp, r7
; CHECK-AAPCS-NEXT:    pop {r4, r5, r6, r7}
; CHECK-AAPCS-NEXT:    pop {r1}
; CHECK-AAPCS-NEXT:    mov r11, r1
; CHECK-AAPCS-NEXT:    pop {pc}
;
; CHECK-FP-AAPCS-LABEL: test_local_vla:
; CHECK-FP-AAPCS:       @ %bb.0: @ %entry
; CHECK-FP-AAPCS-NEXT:    .save {lr}
; CHECK-FP-AAPCS-NEXT:    push {lr}
; CHECK-FP-AAPCS-NEXT:    mov lr, r11
; CHECK-FP-AAPCS-NEXT:    .save {r11}
; CHECK-FP-AAPCS-NEXT:    push {lr}
; CHECK-FP-AAPCS-NEXT:    .setfp r11, sp
; CHECK-FP-AAPCS-NEXT:    mov r11, sp
; CHECK-FP-AAPCS-NEXT:    .save {r4, r5, r6, r7}
; CHECK-FP-AAPCS-NEXT:    push {r4, r5, r6, r7}
; CHECK-FP-AAPCS-NEXT:    .pad #16
; CHECK-FP-AAPCS-NEXT:    sub sp, #16
; CHECK-FP-AAPCS-NEXT:    mov r6, sp
; CHECK-FP-AAPCS-NEXT:    adds r5, r6, #4
; CHECK-FP-AAPCS-NEXT:    lsls r0, r0, #2
; CHECK-FP-AAPCS-NEXT:    adds r0, r0, #7
; CHECK-FP-AAPCS-NEXT:    movs r1, #7
; CHECK-FP-AAPCS-NEXT:    bics r0, r1
; CHECK-FP-AAPCS-NEXT:    mov r1, sp
; CHECK-FP-AAPCS-NEXT:    subs r4, r1, r0
; CHECK-FP-AAPCS-NEXT:    mov sp, r4
; CHECK-FP-AAPCS-NEXT:    adds r0, r6, #7
; CHECK-FP-AAPCS-NEXT:    adds r0, #5
; CHECK-FP-AAPCS-NEXT:    adds r1, r6, #7
; CHECK-FP-AAPCS-NEXT:    adds r1, #1
; CHECK-FP-AAPCS-NEXT:    adds r2, r6, #4
; CHECK-FP-AAPCS-NEXT:    bl h
; CHECK-FP-AAPCS-NEXT:    ldr r3, [r5]
; CHECK-FP-AAPCS-NEXT:    ldr r2, [r5, #4]
; CHECK-FP-AAPCS-NEXT:    ldr r1, [r5, #8]
; CHECK-FP-AAPCS-NEXT:    sub sp, #8
; CHECK-FP-AAPCS-NEXT:    movs r0, #0
; CHECK-FP-AAPCS-NEXT:    str r0, [sp]
; CHECK-FP-AAPCS-NEXT:    str r0, [sp, #4]
; CHECK-FP-AAPCS-NEXT:    mov r0, r4
; CHECK-FP-AAPCS-NEXT:    bl g
; CHECK-FP-AAPCS-NEXT:    add sp, #8
; CHECK-FP-AAPCS-NEXT:    mov r7, r11
; CHECK-FP-AAPCS-NEXT:    subs r7, #16
; CHECK-FP-AAPCS-NEXT:    mov sp, r7
; CHECK-FP-AAPCS-NEXT:    pop {r4, r5, r6, r7}
; CHECK-FP-AAPCS-NEXT:    pop {r1}
; CHECK-FP-AAPCS-NEXT:    mov r11, r1
; CHECK-FP-AAPCS-NEXT:    pop {pc}
entry:
  %x = alloca i32, align 4
  %y = alloca i32, align 4
  %z = alloca i32, align 4
  %vla = alloca i32, i32 %n, align 4
  %call = call i32 @h(ptr nonnull %x, ptr nonnull %y, ptr nonnull %z)
  %0 = load i32, ptr %x, align 4
  %1 = load i32, ptr %y, align 4
  %2 = load i32, ptr %z, align 4
  %call1 = call i32 @g(ptr nonnull %vla, i32 %0, i32 %1, i32 %2, i32 0, i32 0)
  ret i32 %call1
}
; CHECK-LABEL: test_local_vla
; Setup frame pointer
; CHECK-ATPCS: add r7, sp, #12
; CHECK-AAPCS: mov r11, sp
; Locas area
; CHECK-ATPCS: sub sp, #12
; CHECK-AAPCS: sub sp, #16
; Setup base pointer
; CHECK:       mov  r6, sp
; CHECK-ATPCS: mov  r5, r6
; CHECK-AAPCS: adds  r5, r6, #4
; Arguments to `h` compute relative to BP
; CHECK:       adds r0, r6, #7
; CHECK-ATPCS-NEXT:  adds r0, #1
; CHECK-ATPCS-NEXT:  adds r1, r6, #4
; CHECK-ATPCS-NEXT:  mov  r2, r6
; CHECK-AAPCS-NEXT:  adds r0, #5
; CHECK-AAPCS-NEXT:  adds r1, r6, #7
; CHECK-AAPCS-NEXT:  adds r1, #1
; CHECK-AAPCS-NEXT:  adds r2, r6, #4
; CHECK-NEXT:  bl   h
; Load `x`, `y`, `z` via BP (r5 should still have the value of r6 from the move
; above)
; CHECK:       ldr r3, [r5]
; CHECK-NEXT:  ldr r2, [r5, #4]
; CHECK-NEXT:  ldr r1, [r5, #8]
; CHECK:       bl  g

;  Moving SP, access via SP.
; int test_local_moving_sp(int n) {
;   int v[4];
;   int x, y, z;
;   return u(v, &x, &y, s, s) + u(v, &y, &z, s, s);
; }
define dso_local i32 @test_local_moving_sp(i32 %n) local_unnamed_addr {
; CHECK-NOFP-LABEL: test_local_moving_sp:
; CHECK-NOFP:       @ %bb.0: @ %entry
; CHECK-NOFP-NEXT:    .save {r4, r5, r6, r7, lr}
; CHECK-NOFP-NEXT:    push {r4, r5, r6, r7, lr}
; CHECK-NOFP-NEXT:    .pad #36
; CHECK-NOFP-NEXT:    sub sp, #36
; CHECK-NOFP-NEXT:    mov r6, sp
; CHECK-NOFP-NEXT:    sub sp, #508
; CHECK-NOFP-NEXT:    sub sp, #508
; CHECK-NOFP-NEXT:    sub sp, #8
; CHECK-NOFP-NEXT:    ldr r5, .LCPI12_0
; CHECK-NOFP-NEXT:    adds r7, r5, #4
; CHECK-NOFP-NEXT:    mov r0, sp
; CHECK-NOFP-NEXT:    ldr r1, .LCPI12_1
; CHECK-NOFP-NEXT:    mov r2, r7
; CHECK-NOFP-NEXT:    mov r3, r0
; CHECK-NOFP-NEXT:  .LBB12_1: @ %entry
; CHECK-NOFP-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-NOFP-NEXT:    ldr r4, [r2]
; CHECK-NOFP-NEXT:    adds r2, #4
; CHECK-NOFP-NEXT:    str r4, [r3]
; CHECK-NOFP-NEXT:    adds r3, #4
; CHECK-NOFP-NEXT:    subs r1, #4
; CHECK-NOFP-NEXT:    bne .LBB12_1
; CHECK-NOFP-NEXT:  @ %bb.2: @ %entry
; CHECK-NOFP-NEXT:    movs r1, #127
; CHECK-NOFP-NEXT:    lsls r1, r1, #2
; CHECK-NOFP-NEXT:    str r1, [r6, #4] @ 4-byte Spill
; CHECK-NOFP-NEXT:    adds r0, r0, r1
; CHECK-NOFP-NEXT:    ldr r1, .LCPI12_2
; CHECK-NOFP-NEXT:    mov r2, r5
; CHECK-NOFP-NEXT:  .LBB12_3: @ %entry
; CHECK-NOFP-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-NOFP-NEXT:    ldr r3, [r2]
; CHECK-NOFP-NEXT:    adds r2, #4
; CHECK-NOFP-NEXT:    str r3, [r0]
; CHECK-NOFP-NEXT:    adds r0, #4
; CHECK-NOFP-NEXT:    subs r1, #4
; CHECK-NOFP-NEXT:    bne .LBB12_3
; CHECK-NOFP-NEXT:  @ %bb.4: @ %entry
; CHECK-NOFP-NEXT:    ldr r3, [r5]
; CHECK-NOFP-NEXT:    adds r4, r6, #7
; CHECK-NOFP-NEXT:    adds r4, #13
; CHECK-NOFP-NEXT:    adds r1, r6, #7
; CHECK-NOFP-NEXT:    adds r1, #9
; CHECK-NOFP-NEXT:    adds r5, r6, #7
; CHECK-NOFP-NEXT:    adds r5, #5
; CHECK-NOFP-NEXT:    mov r0, r4
; CHECK-NOFP-NEXT:    mov r2, r5
; CHECK-NOFP-NEXT:    bl u
; CHECK-NOFP-NEXT:    add sp, #508
; CHECK-NOFP-NEXT:    add sp, #508
; CHECK-NOFP-NEXT:    add sp, #8
; CHECK-NOFP-NEXT:    str r0, [r6] @ 4-byte Spill
; CHECK-NOFP-NEXT:    sub sp, #508
; CHECK-NOFP-NEXT:    sub sp, #508
; CHECK-NOFP-NEXT:    sub sp, #8
; CHECK-NOFP-NEXT:    mov r0, sp
; CHECK-NOFP-NEXT:    ldr r1, .LCPI12_1
; CHECK-NOFP-NEXT:    mov r2, r0
; CHECK-NOFP-NEXT:  .LBB12_5: @ %entry
; CHECK-NOFP-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-NOFP-NEXT:    ldr r3, [r7]
; CHECK-NOFP-NEXT:    adds r7, #4
; CHECK-NOFP-NEXT:    str r3, [r2]
; CHECK-NOFP-NEXT:    adds r2, #4
; CHECK-NOFP-NEXT:    subs r1, #4
; CHECK-NOFP-NEXT:    bne .LBB12_5
; CHECK-NOFP-NEXT:  @ %bb.6: @ %entry
; CHECK-NOFP-NEXT:    ldr r1, [r6, #4] @ 4-byte Reload
; CHECK-NOFP-NEXT:    adds r0, r0, r1
; CHECK-NOFP-NEXT:    ldr r1, .LCPI12_2
; CHECK-NOFP-NEXT:    ldr r2, .LCPI12_0
; CHECK-NOFP-NEXT:  .LBB12_7: @ %entry
; CHECK-NOFP-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-NOFP-NEXT:    ldr r3, [r2]
; CHECK-NOFP-NEXT:    adds r2, #4
; CHECK-NOFP-NEXT:    str r3, [r0]
; CHECK-NOFP-NEXT:    adds r0, #4
; CHECK-NOFP-NEXT:    subs r1, #4
; CHECK-NOFP-NEXT:    bne .LBB12_7
; CHECK-NOFP-NEXT:  @ %bb.8: @ %entry
; CHECK-NOFP-NEXT:    ldr r0, .LCPI12_0
; CHECK-NOFP-NEXT:    ldr r3, [r0]
; CHECK-NOFP-NEXT:    adds r2, r6, #7
; CHECK-NOFP-NEXT:    adds r2, #1
; CHECK-NOFP-NEXT:    mov r0, r4
; CHECK-NOFP-NEXT:    mov r1, r5
; CHECK-NOFP-NEXT:    bl u
; CHECK-NOFP-NEXT:    add sp, #508
; CHECK-NOFP-NEXT:    add sp, #508
; CHECK-NOFP-NEXT:    add sp, #8
; CHECK-NOFP-NEXT:    ldr r1, [r6] @ 4-byte Reload
; CHECK-NOFP-NEXT:    adds r0, r0, r1
; CHECK-NOFP-NEXT:    add sp, #36
; CHECK-NOFP-NEXT:    pop {r4, r5, r6, r7, pc}
; CHECK-NOFP-NEXT:    .p2align 2
; CHECK-NOFP-NEXT:  @ %bb.9:
; CHECK-NOFP-NEXT:  .LCPI12_0:
; CHECK-NOFP-NEXT:    .long s
; CHECK-NOFP-NEXT:  .LCPI12_1:
; CHECK-NOFP-NEXT:    .long 508 @ 0x1fc
; CHECK-NOFP-NEXT:  .LCPI12_2:
; CHECK-NOFP-NEXT:    .long 512 @ 0x200
;
; CHECK-FP-ATPCS-LABEL: test_local_moving_sp:
; CHECK-FP-ATPCS:       @ %bb.0: @ %entry
; CHECK-FP-ATPCS-NEXT:    .save {r4, r5, r6, r7, lr}
; CHECK-FP-ATPCS-NEXT:    push {r4, r5, r6, r7, lr}
; CHECK-FP-ATPCS-NEXT:    .setfp r7, sp, #12
; CHECK-FP-ATPCS-NEXT:    add r7, sp, #12
; CHECK-FP-ATPCS-NEXT:    .pad #44
; CHECK-FP-ATPCS-NEXT:    sub sp, #44
; CHECK-FP-ATPCS-NEXT:    mov r6, sp
; CHECK-FP-ATPCS-NEXT:    sub sp, #508
; CHECK-FP-ATPCS-NEXT:    sub sp, #508
; CHECK-FP-ATPCS-NEXT:    sub sp, #8
; CHECK-FP-ATPCS-NEXT:    ldr r0, .LCPI12_0
; CHECK-FP-ATPCS-NEXT:    adds r4, r0, #4
; CHECK-FP-ATPCS-NEXT:    mov r0, sp
; CHECK-FP-ATPCS-NEXT:    ldr r1, .LCPI12_1
; CHECK-FP-ATPCS-NEXT:    mov r2, r4
; CHECK-FP-ATPCS-NEXT:    mov r3, r0
; CHECK-FP-ATPCS-NEXT:  .LBB12_1: @ %entry
; CHECK-FP-ATPCS-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-FP-ATPCS-NEXT:    ldr r5, [r2]
; CHECK-FP-ATPCS-NEXT:    adds r2, #4
; CHECK-FP-ATPCS-NEXT:    str r5, [r3]
; CHECK-FP-ATPCS-NEXT:    adds r3, #4
; CHECK-FP-ATPCS-NEXT:    subs r1, #4
; CHECK-FP-ATPCS-NEXT:    bne .LBB12_1
; CHECK-FP-ATPCS-NEXT:  @ %bb.2: @ %entry
; CHECK-FP-ATPCS-NEXT:    movs r1, #127
; CHECK-FP-ATPCS-NEXT:    lsls r1, r1, #2
; CHECK-FP-ATPCS-NEXT:    str r1, [r6, #12] @ 4-byte Spill
; CHECK-FP-ATPCS-NEXT:    adds r0, r0, r1
; CHECK-FP-ATPCS-NEXT:    ldr r1, .LCPI12_2
; CHECK-FP-ATPCS-NEXT:    ldr r2, .LCPI12_0
; CHECK-FP-ATPCS-NEXT:  .LBB12_3: @ %entry
; CHECK-FP-ATPCS-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-FP-ATPCS-NEXT:    ldr r3, [r2]
; CHECK-FP-ATPCS-NEXT:    adds r2, #4
; CHECK-FP-ATPCS-NEXT:    str r3, [r0]
; CHECK-FP-ATPCS-NEXT:    adds r0, #4
; CHECK-FP-ATPCS-NEXT:    subs r1, #4
; CHECK-FP-ATPCS-NEXT:    bne .LBB12_3
; CHECK-FP-ATPCS-NEXT:  @ %bb.4: @ %entry
; CHECK-FP-ATPCS-NEXT:    ldr r0, .LCPI12_0
; CHECK-FP-ATPCS-NEXT:    ldr r3, [r0]
; CHECK-FP-ATPCS-NEXT:    adds r0, r6, #7
; CHECK-FP-ATPCS-NEXT:    adds r0, #21
; CHECK-FP-ATPCS-NEXT:    adds r1, r6, #7
; CHECK-FP-ATPCS-NEXT:    adds r1, #17
; CHECK-FP-ATPCS-NEXT:    adds r5, r6, #7
; CHECK-FP-ATPCS-NEXT:    adds r5, #13
; CHECK-FP-ATPCS-NEXT:    str r0, [r6, #8] @ 4-byte Spill
; CHECK-FP-ATPCS-NEXT:    mov r2, r5
; CHECK-FP-ATPCS-NEXT:    bl u
; CHECK-FP-ATPCS-NEXT:    add sp, #508
; CHECK-FP-ATPCS-NEXT:    add sp, #508
; CHECK-FP-ATPCS-NEXT:    add sp, #8
; CHECK-FP-ATPCS-NEXT:    str r0, [r6, #4] @ 4-byte Spill
; CHECK-FP-ATPCS-NEXT:    sub sp, #508
; CHECK-FP-ATPCS-NEXT:    sub sp, #508
; CHECK-FP-ATPCS-NEXT:    sub sp, #8
; CHECK-FP-ATPCS-NEXT:    mov r0, sp
; CHECK-FP-ATPCS-NEXT:    ldr r1, .LCPI12_1
; CHECK-FP-ATPCS-NEXT:    mov r2, r0
; CHECK-FP-ATPCS-NEXT:  .LBB12_5: @ %entry
; CHECK-FP-ATPCS-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-FP-ATPCS-NEXT:    ldr r3, [r4]
; CHECK-FP-ATPCS-NEXT:    adds r4, #4
; CHECK-FP-ATPCS-NEXT:    str r3, [r2]
; CHECK-FP-ATPCS-NEXT:    adds r2, #4
; CHECK-FP-ATPCS-NEXT:    subs r1, #4
; CHECK-FP-ATPCS-NEXT:    bne .LBB12_5
; CHECK-FP-ATPCS-NEXT:  @ %bb.6: @ %entry
; CHECK-FP-ATPCS-NEXT:    ldr r1, [r6, #12] @ 4-byte Reload
; CHECK-FP-ATPCS-NEXT:    adds r0, r0, r1
; CHECK-FP-ATPCS-NEXT:    ldr r1, .LCPI12_2
; CHECK-FP-ATPCS-NEXT:    ldr r2, .LCPI12_0
; CHECK-FP-ATPCS-NEXT:  .LBB12_7: @ %entry
; CHECK-FP-ATPCS-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-FP-ATPCS-NEXT:    ldr r3, [r2]
; CHECK-FP-ATPCS-NEXT:    adds r2, #4
; CHECK-FP-ATPCS-NEXT:    str r3, [r0]
; CHECK-FP-ATPCS-NEXT:    adds r0, #4
; CHECK-FP-ATPCS-NEXT:    subs r1, #4
; CHECK-FP-ATPCS-NEXT:    bne .LBB12_7
; CHECK-FP-ATPCS-NEXT:  @ %bb.8: @ %entry
; CHECK-FP-ATPCS-NEXT:    ldr r0, .LCPI12_0
; CHECK-FP-ATPCS-NEXT:    ldr r3, [r0]
; CHECK-FP-ATPCS-NEXT:    adds r2, r6, #7
; CHECK-FP-ATPCS-NEXT:    adds r2, #9
; CHECK-FP-ATPCS-NEXT:    ldr r0, [r6, #8] @ 4-byte Reload
; CHECK-FP-ATPCS-NEXT:    mov r1, r5
; CHECK-FP-ATPCS-NEXT:    bl u
; CHECK-FP-ATPCS-NEXT:    add sp, #508
; CHECK-FP-ATPCS-NEXT:    add sp, #508
; CHECK-FP-ATPCS-NEXT:    add sp, #8
; CHECK-FP-ATPCS-NEXT:    ldr r1, [r6, #4] @ 4-byte Reload
; CHECK-FP-ATPCS-NEXT:    adds r0, r0, r1
; CHECK-FP-ATPCS-NEXT:    add sp, #44
; CHECK-FP-ATPCS-NEXT:    pop {r4, r5, r6, r7, pc}
; CHECK-FP-ATPCS-NEXT:    .p2align 2
; CHECK-FP-ATPCS-NEXT:  @ %bb.9:
; CHECK-FP-ATPCS-NEXT:  .LCPI12_0:
; CHECK-FP-ATPCS-NEXT:    .long s
; CHECK-FP-ATPCS-NEXT:  .LCPI12_1:
; CHECK-FP-ATPCS-NEXT:    .long 508 @ 0x1fc
; CHECK-FP-ATPCS-NEXT:  .LCPI12_2:
; CHECK-FP-ATPCS-NEXT:    .long 512 @ 0x200
;
; CHECK-FP-AAPCS-LABEL: test_local_moving_sp:
; CHECK-FP-AAPCS:       @ %bb.0: @ %entry
; CHECK-FP-AAPCS-NEXT:    .save {lr}
; CHECK-FP-AAPCS-NEXT:    push {lr}
; CHECK-FP-AAPCS-NEXT:    mov lr, r11
; CHECK-FP-AAPCS-NEXT:    .save {r11}
; CHECK-FP-AAPCS-NEXT:    push {lr}
; CHECK-FP-AAPCS-NEXT:    .setfp r11, sp
; CHECK-FP-AAPCS-NEXT:    mov r11, sp
; CHECK-FP-AAPCS-NEXT:    .save {r4, r5, r6, r7}
; CHECK-FP-AAPCS-NEXT:    push {r4, r5, r6, r7}
; CHECK-FP-AAPCS-NEXT:    .pad #40
; CHECK-FP-AAPCS-NEXT:    sub sp, #40
; CHECK-FP-AAPCS-NEXT:    mov r6, sp
; CHECK-FP-AAPCS-NEXT:    sub sp, #508
; CHECK-FP-AAPCS-NEXT:    sub sp, #508
; CHECK-FP-AAPCS-NEXT:    sub sp, #8
; CHECK-FP-AAPCS-NEXT:    ldr r5, .LCPI12_0
; CHECK-FP-AAPCS-NEXT:    adds r7, r5, #4
; CHECK-FP-AAPCS-NEXT:    mov r0, sp
; CHECK-FP-AAPCS-NEXT:    ldr r1, .LCPI12_1
; CHECK-FP-AAPCS-NEXT:    mov r2, r7
; CHECK-FP-AAPCS-NEXT:    mov r3, r0
; CHECK-FP-AAPCS-NEXT:  .LBB12_1: @ %entry
; CHECK-FP-AAPCS-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-FP-AAPCS-NEXT:    ldr r4, [r2]
; CHECK-FP-AAPCS-NEXT:    adds r2, #4
; CHECK-FP-AAPCS-NEXT:    str r4, [r3]
; CHECK-FP-AAPCS-NEXT:    adds r3, #4
; CHECK-FP-AAPCS-NEXT:    subs r1, #4
; CHECK-FP-AAPCS-NEXT:    bne .LBB12_1
; CHECK-FP-AAPCS-NEXT:  @ %bb.2: @ %entry
; CHECK-FP-AAPCS-NEXT:    movs r1, #127
; CHECK-FP-AAPCS-NEXT:    lsls r1, r1, #2
; CHECK-FP-AAPCS-NEXT:    str r1, [r6, #8] @ 4-byte Spill
; CHECK-FP-AAPCS-NEXT:    adds r0, r0, r1
; CHECK-FP-AAPCS-NEXT:    ldr r1, .LCPI12_2
; CHECK-FP-AAPCS-NEXT:    mov r2, r5
; CHECK-FP-AAPCS-NEXT:  .LBB12_3: @ %entry
; CHECK-FP-AAPCS-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-FP-AAPCS-NEXT:    ldr r3, [r2]
; CHECK-FP-AAPCS-NEXT:    adds r2, #4
; CHECK-FP-AAPCS-NEXT:    str r3, [r0]
; CHECK-FP-AAPCS-NEXT:    adds r0, #4
; CHECK-FP-AAPCS-NEXT:    subs r1, #4
; CHECK-FP-AAPCS-NEXT:    bne .LBB12_3
; CHECK-FP-AAPCS-NEXT:  @ %bb.4: @ %entry
; CHECK-FP-AAPCS-NEXT:    ldr r3, [r5]
; CHECK-FP-AAPCS-NEXT:    adds r4, r6, #7
; CHECK-FP-AAPCS-NEXT:    adds r4, #17
; CHECK-FP-AAPCS-NEXT:    adds r1, r6, #7
; CHECK-FP-AAPCS-NEXT:    adds r1, #13
; CHECK-FP-AAPCS-NEXT:    adds r5, r6, #7
; CHECK-FP-AAPCS-NEXT:    adds r5, #9
; CHECK-FP-AAPCS-NEXT:    mov r0, r4
; CHECK-FP-AAPCS-NEXT:    mov r2, r5
; CHECK-FP-AAPCS-NEXT:    bl u
; CHECK-FP-AAPCS-NEXT:    add sp, #508
; CHECK-FP-AAPCS-NEXT:    add sp, #508
; CHECK-FP-AAPCS-NEXT:    add sp, #8
; CHECK-FP-AAPCS-NEXT:    str r0, [r6, #4] @ 4-byte Spill
; CHECK-FP-AAPCS-NEXT:    sub sp, #508
; CHECK-FP-AAPCS-NEXT:    sub sp, #508
; CHECK-FP-AAPCS-NEXT:    sub sp, #8
; CHECK-FP-AAPCS-NEXT:    mov r0, sp
; CHECK-FP-AAPCS-NEXT:    ldr r1, .LCPI12_1
; CHECK-FP-AAPCS-NEXT:    mov r2, r0
; CHECK-FP-AAPCS-NEXT:  .LBB12_5: @ %entry
; CHECK-FP-AAPCS-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-FP-AAPCS-NEXT:    ldr r3, [r7]
; CHECK-FP-AAPCS-NEXT:    adds r7, #4
; CHECK-FP-AAPCS-NEXT:    str r3, [r2]
; CHECK-FP-AAPCS-NEXT:    adds r2, #4
; CHECK-FP-AAPCS-NEXT:    subs r1, #4
; CHECK-FP-AAPCS-NEXT:    bne .LBB12_5
; CHECK-FP-AAPCS-NEXT:  @ %bb.6: @ %entry
; CHECK-FP-AAPCS-NEXT:    ldr r1, [r6, #8] @ 4-byte Reload
; CHECK-FP-AAPCS-NEXT:    adds r0, r0, r1
; CHECK-FP-AAPCS-NEXT:    ldr r1, .LCPI12_2
; CHECK-FP-AAPCS-NEXT:    ldr r2, .LCPI12_0
; CHECK-FP-AAPCS-NEXT:  .LBB12_7: @ %entry
; CHECK-FP-AAPCS-NEXT:    @ =>This Inner Loop Header: Depth=1
; CHECK-FP-AAPCS-NEXT:    ldr r3, [r2]
; CHECK-FP-AAPCS-NEXT:    adds r2, #4
; CHECK-FP-AAPCS-NEXT:    str r3, [r0]
; CHECK-FP-AAPCS-NEXT:    adds r0, #4
; CHECK-FP-AAPCS-NEXT:    subs r1, #4
; CHECK-FP-AAPCS-NEXT:    bne .LBB12_7
; CHECK-FP-AAPCS-NEXT:  @ %bb.8: @ %entry
; CHECK-FP-AAPCS-NEXT:    ldr r0, .LCPI12_0
; CHECK-FP-AAPCS-NEXT:    ldr r3, [r0]
; CHECK-FP-AAPCS-NEXT:    adds r2, r6, #7
; CHECK-FP-AAPCS-NEXT:    adds r2, #5
; CHECK-FP-AAPCS-NEXT:    mov r0, r4
; CHECK-FP-AAPCS-NEXT:    mov r1, r5
; CHECK-FP-AAPCS-NEXT:    bl u
; CHECK-FP-AAPCS-NEXT:    add sp, #508
; CHECK-FP-AAPCS-NEXT:    add sp, #508
; CHECK-FP-AAPCS-NEXT:    add sp, #8
; CHECK-FP-AAPCS-NEXT:    ldr r1, [r6, #4] @ 4-byte Reload
; CHECK-FP-AAPCS-NEXT:    adds r0, r0, r1
; CHECK-FP-AAPCS-NEXT:    add sp, #40
; CHECK-FP-AAPCS-NEXT:    pop {r4, r5, r6, r7}
; CHECK-FP-AAPCS-NEXT:    pop {r1}
; CHECK-FP-AAPCS-NEXT:    mov r11, r1
; CHECK-FP-AAPCS-NEXT:    pop {pc}
; CHECK-FP-AAPCS-NEXT:    .p2align 2
; CHECK-FP-AAPCS-NEXT:  @ %bb.9:
; CHECK-FP-AAPCS-NEXT:  .LCPI12_0:
; CHECK-FP-AAPCS-NEXT:    .long s
; CHECK-FP-AAPCS-NEXT:  .LCPI12_1:
; CHECK-FP-AAPCS-NEXT:    .long 508 @ 0x1fc
; CHECK-FP-AAPCS-NEXT:  .LCPI12_2:
; CHECK-FP-AAPCS-NEXT:    .long 512 @ 0x200
entry:
  %v = alloca [4 x i32], align 4
  %x = alloca i32, align 4
  %y = alloca i32, align 4
  %z = alloca i32, align 4
  %call = call i32 @u(ptr nonnull %v, ptr nonnull %x, ptr nonnull %y, ptr byval(%struct.S) nonnull align 4 @s, ptr byval(%struct.S) nonnull align 4 @s)
  %call2 = call i32 @u(ptr nonnull %v, ptr nonnull %y, ptr nonnull %z, ptr byval(%struct.S) nonnull align 4 @s, ptr byval(%struct.S) nonnull align 4 @s)
  %add = add nsw i32 %call2, %call
  ret i32 %add
}
; CHECK-LABEL: test_local_moving_sp
; Locals area
; CHECK-NOFP: sub sp, #36
; CHECK-FP-ATPCS: sub sp, #44
; CHECK-FP-AAPCS: sub sp, #40
; Setup BP
; CHECK:      mov r6, sp
; Outoging arguments
; CHECK:      sub sp, #508
; CHECK-NEXT: sub sp, #508
; CHECK-NEXT: sub sp, #8
; Argument addresses computed relative to BP
; CHECK-NOFP:      adds r4, r6, #7
; CHECK-NOFP-NEXT: adds r4, #13
; CHECK-NOFP:      adds r1, r6, #7
; CHECK-NOFP-NEXT: adds r1, #9
; CHECK-NOFP:      adds r5, r6, #7
; CHECK-NOFP-NEXT: adds r5, #5
; CHECK-FP-ATPCS:      adds r0, r6, #7
; CHECK-FP-ATPCS-NEXT: adds r0, #21
; CHECK-FP-ATPCS:      adds r1, r6, #7
; CHECK-FP-ATPCS-NEXT: adds r1, #17
; CHECK-FP-ATPCS:      adds r5, r6, #7
; CHECK-FP-ATPCS-NEXT: adds r5, #13
; CHECK-FP-AAPCS:      adds r4, r6, #7
; CHECK-FP-AAPCS-NEXT: adds r4, #17
; CHECK-FP-AAPCS:      adds r1, r6, #7
; CHECK-FP-AAPCS-NEXT: adds r1, #13
; CHECK-FP-AAPCS:      adds r5, r6, #7
; CHECK-FP-AAPCS-NEXT: adds r5, #9
; CHECK:      bl   u
; Stack restored before next call
; CHECK:      add  sp, #508
; CHECK-NEXT: add  sp, #508
; CHECK-NEXT: add  sp, #8
; CHECK:      bl   u
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
