; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -verify-machineinstrs -mattr=+q \
; RUN:     -target-abi ilp32q < %s \
; RUN:   | FileCheck -check-prefix=RV32-ILP32Q %s

; This file contains tests that will have differing output for the ilp32/ilp32f
; and ilp32d ABIs.

define i32 @callee_fp128_in_fpr(i32 %a, fp128 %b) nounwind {
; RV32-ILP32Q-LABEL: callee_fp128_in_fpr:
; RV32-ILP32Q:       # %bb.0:
; RV32-ILP32Q-NEXT:    addi sp, sp, -32
; RV32-ILP32Q-NEXT:    sw ra, 28(sp) # 4-byte Folded Spill
; RV32-ILP32Q-NEXT:    sw s0, 24(sp) # 4-byte Folded Spill
; RV32-ILP32Q-NEXT:    lw a2, 0(a1)
; RV32-ILP32Q-NEXT:    lw a3, 4(a1)
; RV32-ILP32Q-NEXT:    lw a4, 8(a1)
; RV32-ILP32Q-NEXT:    lw a1, 12(a1)
; RV32-ILP32Q-NEXT:    mv s0, a0
; RV32-ILP32Q-NEXT:    addi a0, sp, 8
; RV32-ILP32Q-NEXT:    sw a2, 8(sp)
; RV32-ILP32Q-NEXT:    sw a3, 12(sp)
; RV32-ILP32Q-NEXT:    sw a4, 16(sp)
; RV32-ILP32Q-NEXT:    sw a1, 20(sp)
; RV32-ILP32Q-NEXT:    call __fixtfsi
; RV32-ILP32Q-NEXT:    add a0, s0, a0
; RV32-ILP32Q-NEXT:    lw ra, 28(sp) # 4-byte Folded Reload
; RV32-ILP32Q-NEXT:    lw s0, 24(sp) # 4-byte Folded Reload
; RV32-ILP32Q-NEXT:    addi sp, sp, 32
; RV32-ILP32Q-NEXT:    ret
  %b_fptosi = fptosi fp128 %b to i32
  %1 = add i32 %a, %b_fptosi
  ret i32 %1
}

define i32 @caller_fp128_in_fpr() nounwind {
; RV32-ILP32Q-LABEL: caller_fp128_in_fpr:
; RV32-ILP32Q:       # %bb.0:
; RV32-ILP32Q-NEXT:    addi sp, sp, -32
; RV32-ILP32Q-NEXT:    sw ra, 28(sp) # 4-byte Folded Spill
; RV32-ILP32Q-NEXT:    lui a2, 262144
; RV32-ILP32Q-NEXT:    li a0, 1
; RV32-ILP32Q-NEXT:    mv a1, sp
; RV32-ILP32Q-NEXT:    sw zero, 0(sp)
; RV32-ILP32Q-NEXT:    sw zero, 4(sp)
; RV32-ILP32Q-NEXT:    sw zero, 8(sp)
; RV32-ILP32Q-NEXT:    sw a2, 12(sp)
; RV32-ILP32Q-NEXT:    call callee_fp128_in_fpr
; RV32-ILP32Q-NEXT:    lw ra, 28(sp) # 4-byte Folded Reload
; RV32-ILP32Q-NEXT:    addi sp, sp, 32
; RV32-ILP32Q-NEXT:    ret
  %1 = fpext double 2.0 to fp128
  %2 = call i32 @callee_fp128_in_fpr(i32 1, fp128 %1)
  ret i32 %2
}

; Must keep define on a single line due to an update_llc_test_checks.py limitation
define i32 @callee_fp128_in_fpr_exhausted_gprs(i64 %a, i64 %b, i64 %c, i64 %d, i32 %e, fp128 %f) nounwind {
; RV32-ILP32Q-LABEL: callee_fp128_in_fpr_exhausted_gprs:
; RV32-ILP32Q:       # %bb.0:
; RV32-ILP32Q-NEXT:    addi sp, sp, -32
; RV32-ILP32Q-NEXT:    sw ra, 28(sp) # 4-byte Folded Spill
; RV32-ILP32Q-NEXT:    sw s0, 24(sp) # 4-byte Folded Spill
; RV32-ILP32Q-NEXT:    lw a0, 36(sp)
; RV32-ILP32Q-NEXT:    lw a1, 0(a0)
; RV32-ILP32Q-NEXT:    lw a2, 4(a0)
; RV32-ILP32Q-NEXT:    lw a3, 8(a0)
; RV32-ILP32Q-NEXT:    lw a4, 12(a0)
; RV32-ILP32Q-NEXT:    lw s0, 32(sp)
; RV32-ILP32Q-NEXT:    addi a0, sp, 8
; RV32-ILP32Q-NEXT:    sw a1, 8(sp)
; RV32-ILP32Q-NEXT:    sw a2, 12(sp)
; RV32-ILP32Q-NEXT:    sw a3, 16(sp)
; RV32-ILP32Q-NEXT:    sw a4, 20(sp)
; RV32-ILP32Q-NEXT:    call __fixtfsi
; RV32-ILP32Q-NEXT:    add a0, s0, a0
; RV32-ILP32Q-NEXT:    lw ra, 28(sp) # 4-byte Folded Reload
; RV32-ILP32Q-NEXT:    lw s0, 24(sp) # 4-byte Folded Reload
; RV32-ILP32Q-NEXT:    addi sp, sp, 32
; RV32-ILP32Q-NEXT:    ret
  %f_fptosi = fptosi fp128 %f to i32
  %1 = add i32 %e, %f_fptosi
  ret i32 %1
}

define i32 @caller_fp128_in_fpr_exhausted_gprs() nounwind {
; RV32-ILP32Q-LABEL: caller_fp128_in_fpr_exhausted_gprs:
; RV32-ILP32Q:       # %bb.0:
; RV32-ILP32Q-NEXT:    addi sp, sp, -48
; RV32-ILP32Q-NEXT:    sw ra, 44(sp) # 4-byte Folded Spill
; RV32-ILP32Q-NEXT:    addi a1, sp, 16
; RV32-ILP32Q-NEXT:    li a3, 5
; RV32-ILP32Q-NEXT:    lui a5, 262168
; RV32-ILP32Q-NEXT:    li a0, 1
; RV32-ILP32Q-NEXT:    li a2, 2
; RV32-ILP32Q-NEXT:    li a4, 3
; RV32-ILP32Q-NEXT:    li a6, 4
; RV32-ILP32Q-NEXT:    sw a3, 0(sp)
; RV32-ILP32Q-NEXT:    sw a1, 4(sp)
; RV32-ILP32Q-NEXT:    sw zero, 16(sp)
; RV32-ILP32Q-NEXT:    sw zero, 20(sp)
; RV32-ILP32Q-NEXT:    sw zero, 24(sp)
; RV32-ILP32Q-NEXT:    sw a5, 28(sp)
; RV32-ILP32Q-NEXT:    li a1, 0
; RV32-ILP32Q-NEXT:    li a3, 0
; RV32-ILP32Q-NEXT:    li a5, 0
; RV32-ILP32Q-NEXT:    li a7, 0
; RV32-ILP32Q-NEXT:    call callee_fp128_in_fpr_exhausted_gprs
; RV32-ILP32Q-NEXT:    lw ra, 44(sp) # 4-byte Folded Reload
; RV32-ILP32Q-NEXT:    addi sp, sp, 48
; RV32-ILP32Q-NEXT:    ret
  %1 = fpext double 6.0 to fp128
  %2 = call i32 @callee_fp128_in_fpr_exhausted_gprs(
      i64 1, i64 2, i64 3, i64 4, i32 5, fp128 %1)
  ret i32 %2
}

; Must keep define on a single line due to an update_llc_test_checks.py limitation
define i32 @callee_fp128_in_gpr_exhausted_fprs(fp128 %a, fp128 %b, fp128 %c, fp128 %d, fp128 %e, fp128 %f, fp128 %g, fp128 %h, fp128 %i) nounwind {
; RV32-ILP32Q-LABEL: callee_fp128_in_gpr_exhausted_fprs:
; RV32-ILP32Q:       # %bb.0:
; RV32-ILP32Q-NEXT:    addi sp, sp, -64
; RV32-ILP32Q-NEXT:    sw ra, 60(sp) # 4-byte Folded Spill
; RV32-ILP32Q-NEXT:    sw s0, 56(sp) # 4-byte Folded Spill
; RV32-ILP32Q-NEXT:    sw s1, 52(sp) # 4-byte Folded Spill
; RV32-ILP32Q-NEXT:    sw s2, 48(sp) # 4-byte Folded Spill
; RV32-ILP32Q-NEXT:    sw s3, 44(sp) # 4-byte Folded Spill
; RV32-ILP32Q-NEXT:    sw s4, 40(sp) # 4-byte Folded Spill
; RV32-ILP32Q-NEXT:    lw a0, 64(sp)
; RV32-ILP32Q-NEXT:    lw s1, 0(a0)
; RV32-ILP32Q-NEXT:    lw s2, 4(a0)
; RV32-ILP32Q-NEXT:    lw s3, 8(a0)
; RV32-ILP32Q-NEXT:    lw s4, 12(a0)
; RV32-ILP32Q-NEXT:    lw a1, 0(a7)
; RV32-ILP32Q-NEXT:    lw a2, 4(a7)
; RV32-ILP32Q-NEXT:    lw a3, 8(a7)
; RV32-ILP32Q-NEXT:    lw a4, 12(a7)
; RV32-ILP32Q-NEXT:    addi a0, sp, 24
; RV32-ILP32Q-NEXT:    sw a1, 24(sp)
; RV32-ILP32Q-NEXT:    sw a2, 28(sp)
; RV32-ILP32Q-NEXT:    sw a3, 32(sp)
; RV32-ILP32Q-NEXT:    sw a4, 36(sp)
; RV32-ILP32Q-NEXT:    call __fixtfsi
; RV32-ILP32Q-NEXT:    mv s0, a0
; RV32-ILP32Q-NEXT:    addi a0, sp, 8
; RV32-ILP32Q-NEXT:    sw s1, 8(sp)
; RV32-ILP32Q-NEXT:    sw s2, 12(sp)
; RV32-ILP32Q-NEXT:    sw s3, 16(sp)
; RV32-ILP32Q-NEXT:    sw s4, 20(sp)
; RV32-ILP32Q-NEXT:    call __fixtfsi
; RV32-ILP32Q-NEXT:    add a0, s0, a0
; RV32-ILP32Q-NEXT:    lw ra, 60(sp) # 4-byte Folded Reload
; RV32-ILP32Q-NEXT:    lw s0, 56(sp) # 4-byte Folded Reload
; RV32-ILP32Q-NEXT:    lw s1, 52(sp) # 4-byte Folded Reload
; RV32-ILP32Q-NEXT:    lw s2, 48(sp) # 4-byte Folded Reload
; RV32-ILP32Q-NEXT:    lw s3, 44(sp) # 4-byte Folded Reload
; RV32-ILP32Q-NEXT:    lw s4, 40(sp) # 4-byte Folded Reload
; RV32-ILP32Q-NEXT:    addi sp, sp, 64
; RV32-ILP32Q-NEXT:    ret
  %h_fptosi = fptosi fp128 %h to i32
  %i_fptosi = fptosi fp128 %i to i32
  %1 = add i32 %h_fptosi, %i_fptosi
  ret i32 %1
}

define i32 @caller_fp128_in_gpr_exhausted_fprs() nounwind {
; RV32-ILP32Q-LABEL: caller_fp128_in_gpr_exhausted_fprs:
; RV32-ILP32Q:       # %bb.0:
; RV32-ILP32Q-NEXT:    addi sp, sp, -176
; RV32-ILP32Q-NEXT:    sw ra, 172(sp) # 4-byte Folded Spill
; RV32-ILP32Q-NEXT:    addi a0, sp, 16
; RV32-ILP32Q-NEXT:    lui t0, 262178
; RV32-ILP32Q-NEXT:    lui a1, 262176
; RV32-ILP32Q-NEXT:    lui a2, 262172
; RV32-ILP32Q-NEXT:    lui a3, 262168
; RV32-ILP32Q-NEXT:    lui a4, 262164
; RV32-ILP32Q-NEXT:    lui a5, 262160
; RV32-ILP32Q-NEXT:    lui a6, 262152
; RV32-ILP32Q-NEXT:    lui a7, 262144
; RV32-ILP32Q-NEXT:    sw a0, 0(sp)
; RV32-ILP32Q-NEXT:    lui t1, 262128
; RV32-ILP32Q-NEXT:    sw zero, 16(sp)
; RV32-ILP32Q-NEXT:    sw zero, 20(sp)
; RV32-ILP32Q-NEXT:    sw zero, 24(sp)
; RV32-ILP32Q-NEXT:    sw t0, 28(sp)
; RV32-ILP32Q-NEXT:    addi a0, sp, 144
; RV32-ILP32Q-NEXT:    sw zero, 32(sp)
; RV32-ILP32Q-NEXT:    sw zero, 36(sp)
; RV32-ILP32Q-NEXT:    sw zero, 40(sp)
; RV32-ILP32Q-NEXT:    sw a1, 44(sp)
; RV32-ILP32Q-NEXT:    addi a1, sp, 128
; RV32-ILP32Q-NEXT:    sw zero, 48(sp)
; RV32-ILP32Q-NEXT:    sw zero, 52(sp)
; RV32-ILP32Q-NEXT:    sw zero, 56(sp)
; RV32-ILP32Q-NEXT:    sw a2, 60(sp)
; RV32-ILP32Q-NEXT:    addi a2, sp, 112
; RV32-ILP32Q-NEXT:    sw zero, 64(sp)
; RV32-ILP32Q-NEXT:    sw zero, 68(sp)
; RV32-ILP32Q-NEXT:    sw zero, 72(sp)
; RV32-ILP32Q-NEXT:    sw a3, 76(sp)
; RV32-ILP32Q-NEXT:    addi a3, sp, 96
; RV32-ILP32Q-NEXT:    sw zero, 80(sp)
; RV32-ILP32Q-NEXT:    sw zero, 84(sp)
; RV32-ILP32Q-NEXT:    sw zero, 88(sp)
; RV32-ILP32Q-NEXT:    sw a4, 92(sp)
; RV32-ILP32Q-NEXT:    addi a4, sp, 80
; RV32-ILP32Q-NEXT:    sw zero, 96(sp)
; RV32-ILP32Q-NEXT:    sw zero, 100(sp)
; RV32-ILP32Q-NEXT:    sw zero, 104(sp)
; RV32-ILP32Q-NEXT:    sw a5, 108(sp)
; RV32-ILP32Q-NEXT:    addi a5, sp, 64
; RV32-ILP32Q-NEXT:    sw zero, 112(sp)
; RV32-ILP32Q-NEXT:    sw zero, 116(sp)
; RV32-ILP32Q-NEXT:    sw zero, 120(sp)
; RV32-ILP32Q-NEXT:    sw a6, 124(sp)
; RV32-ILP32Q-NEXT:    addi a6, sp, 48
; RV32-ILP32Q-NEXT:    sw zero, 128(sp)
; RV32-ILP32Q-NEXT:    sw zero, 132(sp)
; RV32-ILP32Q-NEXT:    sw zero, 136(sp)
; RV32-ILP32Q-NEXT:    sw a7, 140(sp)
; RV32-ILP32Q-NEXT:    addi a7, sp, 32
; RV32-ILP32Q-NEXT:    sw zero, 144(sp)
; RV32-ILP32Q-NEXT:    sw zero, 148(sp)
; RV32-ILP32Q-NEXT:    sw zero, 152(sp)
; RV32-ILP32Q-NEXT:    sw t1, 156(sp)
; RV32-ILP32Q-NEXT:    call callee_fp128_in_gpr_exhausted_fprs
; RV32-ILP32Q-NEXT:    lw ra, 172(sp) # 4-byte Folded Reload
; RV32-ILP32Q-NEXT:    addi sp, sp, 176
; RV32-ILP32Q-NEXT:    ret
  %1 = fpext double 1.0 to fp128
  %2 = fpext double 2.0 to fp128
  %3 = fpext double 3.0 to fp128
  %4 = fpext double 4.0 to fp128
  %5 = fpext double 5.0 to fp128
  %6 = fpext double 6.0 to fp128
  %7 = fpext double 7.0 to fp128
  %8 = fpext double 8.0 to fp128
  %9 = fpext double 9.0 to fp128
  %10 = call i32 @callee_fp128_in_gpr_exhausted_fprs(
      fp128 %1, fp128 %2, fp128 %3, fp128 %4, fp128 %5, fp128 %6,
      fp128 %7, fp128 %8, fp128 %9)
  ret i32 %10
}

; Must keep define on a single line due to an update_llc_test_checks.py limitation
define i32 @callee_fp128_in_gpr_and_stack_almost_exhausted_gprs_fprs(i64 %a, fp128 %b, i64 %c, fp128 %d, i64 %e, fp128 %f, i32 %g, fp128 %h, fp128 %i, fp128 %j, fp128 %k, fp128 %l, fp128 %m) nounwind {
; RV32-ILP32Q-LABEL: callee_fp128_in_gpr_and_stack_almost_exhausted_gprs_fprs:
; RV32-ILP32Q:       # %bb.0:
; RV32-ILP32Q-NEXT:    addi sp, sp, -32
; RV32-ILP32Q-NEXT:    sw ra, 28(sp) # 4-byte Folded Spill
; RV32-ILP32Q-NEXT:    sw s0, 24(sp) # 4-byte Folded Spill
; RV32-ILP32Q-NEXT:    lw a0, 60(sp)
; RV32-ILP32Q-NEXT:    lw a1, 0(a0)
; RV32-ILP32Q-NEXT:    lw a2, 4(a0)
; RV32-ILP32Q-NEXT:    lw a3, 8(a0)
; RV32-ILP32Q-NEXT:    lw a4, 12(a0)
; RV32-ILP32Q-NEXT:    lw s0, 36(sp)
; RV32-ILP32Q-NEXT:    addi a0, sp, 8
; RV32-ILP32Q-NEXT:    sw a1, 8(sp)
; RV32-ILP32Q-NEXT:    sw a2, 12(sp)
; RV32-ILP32Q-NEXT:    sw a3, 16(sp)
; RV32-ILP32Q-NEXT:    sw a4, 20(sp)
; RV32-ILP32Q-NEXT:    call __fixtfsi
; RV32-ILP32Q-NEXT:    add a0, s0, a0
; RV32-ILP32Q-NEXT:    lw ra, 28(sp) # 4-byte Folded Reload
; RV32-ILP32Q-NEXT:    lw s0, 24(sp) # 4-byte Folded Reload
; RV32-ILP32Q-NEXT:    addi sp, sp, 32
; RV32-ILP32Q-NEXT:    ret
  %m_fptosi = fptosi fp128 %m to i32
  %1 = add i32 %g, %m_fptosi
  ret i32 %1
}

define i32 @caller_fp128_in_gpr_and_stack_almost_exhausted_gprs_fprs() nounwind {
; RV32-ILP32Q-LABEL: caller_fp128_in_gpr_and_stack_almost_exhausted_gprs_fprs:
; RV32-ILP32Q:       # %bb.0:
; RV32-ILP32Q-NEXT:    addi sp, sp, -192
; RV32-ILP32Q-NEXT:    sw ra, 188(sp) # 4-byte Folded Spill
; RV32-ILP32Q-NEXT:    addi a0, sp, 32
; RV32-ILP32Q-NEXT:    addi a5, sp, 48
; RV32-ILP32Q-NEXT:    addi a6, sp, 64
; RV32-ILP32Q-NEXT:    addi a7, sp, 80
; RV32-ILP32Q-NEXT:    addi t0, sp, 96
; RV32-ILP32Q-NEXT:    addi t1, sp, 112
; RV32-ILP32Q-NEXT:    li t2, 7
; RV32-ILP32Q-NEXT:    addi t3, sp, 128
; RV32-ILP32Q-NEXT:    lui t4, 262186
; RV32-ILP32Q-NEXT:    lui t5, 262184
; RV32-ILP32Q-NEXT:    lui a2, 262182
; RV32-ILP32Q-NEXT:    lui a3, 262180
; RV32-ILP32Q-NEXT:    lui a4, 262178
; RV32-ILP32Q-NEXT:    lui a1, 262176
; RV32-ILP32Q-NEXT:    sw a7, 16(sp)
; RV32-ILP32Q-NEXT:    sw a6, 20(sp)
; RV32-ILP32Q-NEXT:    sw a5, 24(sp)
; RV32-ILP32Q-NEXT:    sw a0, 28(sp)
; RV32-ILP32Q-NEXT:    lui a7, 262168
; RV32-ILP32Q-NEXT:    sw t3, 0(sp)
; RV32-ILP32Q-NEXT:    sw t2, 4(sp)
; RV32-ILP32Q-NEXT:    sw t1, 8(sp)
; RV32-ILP32Q-NEXT:    sw t0, 12(sp)
; RV32-ILP32Q-NEXT:    lui t0, 262160
; RV32-ILP32Q-NEXT:    sw zero, 32(sp)
; RV32-ILP32Q-NEXT:    sw zero, 36(sp)
; RV32-ILP32Q-NEXT:    sw zero, 40(sp)
; RV32-ILP32Q-NEXT:    sw t4, 44(sp)
; RV32-ILP32Q-NEXT:    lui t1, 262144
; RV32-ILP32Q-NEXT:    sw zero, 48(sp)
; RV32-ILP32Q-NEXT:    sw zero, 52(sp)
; RV32-ILP32Q-NEXT:    sw zero, 56(sp)
; RV32-ILP32Q-NEXT:    sw t5, 60(sp)
; RV32-ILP32Q-NEXT:    li a0, 1
; RV32-ILP32Q-NEXT:    sw zero, 64(sp)
; RV32-ILP32Q-NEXT:    sw zero, 68(sp)
; RV32-ILP32Q-NEXT:    sw zero, 72(sp)
; RV32-ILP32Q-NEXT:    sw a2, 76(sp)
; RV32-ILP32Q-NEXT:    addi a2, sp, 160
; RV32-ILP32Q-NEXT:    sw zero, 80(sp)
; RV32-ILP32Q-NEXT:    sw zero, 84(sp)
; RV32-ILP32Q-NEXT:    sw zero, 88(sp)
; RV32-ILP32Q-NEXT:    sw a3, 92(sp)
; RV32-ILP32Q-NEXT:    li a3, 3
; RV32-ILP32Q-NEXT:    sw zero, 96(sp)
; RV32-ILP32Q-NEXT:    sw zero, 100(sp)
; RV32-ILP32Q-NEXT:    sw zero, 104(sp)
; RV32-ILP32Q-NEXT:    sw a4, 108(sp)
; RV32-ILP32Q-NEXT:    addi a5, sp, 144
; RV32-ILP32Q-NEXT:    sw zero, 112(sp)
; RV32-ILP32Q-NEXT:    sw zero, 116(sp)
; RV32-ILP32Q-NEXT:    sw zero, 120(sp)
; RV32-ILP32Q-NEXT:    sw a1, 124(sp)
; RV32-ILP32Q-NEXT:    li a6, 5
; RV32-ILP32Q-NEXT:    sw zero, 128(sp)
; RV32-ILP32Q-NEXT:    sw zero, 132(sp)
; RV32-ILP32Q-NEXT:    sw zero, 136(sp)
; RV32-ILP32Q-NEXT:    sw a7, 140(sp)
; RV32-ILP32Q-NEXT:    sw zero, 144(sp)
; RV32-ILP32Q-NEXT:    sw zero, 148(sp)
; RV32-ILP32Q-NEXT:    sw zero, 152(sp)
; RV32-ILP32Q-NEXT:    sw t0, 156(sp)
; RV32-ILP32Q-NEXT:    sw zero, 160(sp)
; RV32-ILP32Q-NEXT:    sw zero, 164(sp)
; RV32-ILP32Q-NEXT:    sw zero, 168(sp)
; RV32-ILP32Q-NEXT:    sw t1, 172(sp)
; RV32-ILP32Q-NEXT:    li a1, 0
; RV32-ILP32Q-NEXT:    li a4, 0
; RV32-ILP32Q-NEXT:    li a7, 0
; RV32-ILP32Q-NEXT:    call callee_fp128_in_gpr_and_stack_almost_exhausted_gprs_fprs
; RV32-ILP32Q-NEXT:    lw ra, 188(sp) # 4-byte Folded Reload
; RV32-ILP32Q-NEXT:    addi sp, sp, 192
; RV32-ILP32Q-NEXT:    ret
  %2 = fpext double 2.0 to fp128
  %4 = fpext double 4.0 to fp128
  %6 = fpext double 6.0 to fp128
  %8 = fpext double 8.0 to fp128
  %9 = fpext double 9.0 to fp128
  %10 = fpext double 10.0 to fp128
  %11 = fpext double 11.0 to fp128
  %12 = fpext double 12.0 to fp128
  %13 = fpext double 13.0 to fp128
  %14 = call i32 @callee_fp128_in_gpr_and_stack_almost_exhausted_gprs_fprs(
      i64 1, fp128 %2, i64 3, fp128 %4, i64 5, fp128 %6, i32 7, fp128 %8,
      fp128 %9, fp128 %10, fp128 %11, fp128 %12, fp128 %13)
  ret i32 %14
}


; Must keep define on a single line due to an update_llc_test_checks.py limitation
define i32 @callee_fp128_on_stack_exhausted_gprs_fprs(i64 %a, fp128 %b, i64 %c, fp128 %d, i64 %e, fp128 %f, i64 %g, fp128 %h, fp128 %i, fp128 %j, fp128 %k, fp128 %l, fp128 %m) nounwind {
; RV32-ILP32Q-LABEL: callee_fp128_on_stack_exhausted_gprs_fprs:
; RV32-ILP32Q:       # %bb.0:
; RV32-ILP32Q-NEXT:    addi sp, sp, -32
; RV32-ILP32Q-NEXT:    sw ra, 28(sp) # 4-byte Folded Spill
; RV32-ILP32Q-NEXT:    sw s0, 24(sp) # 4-byte Folded Spill
; RV32-ILP32Q-NEXT:    lw a0, 68(sp)
; RV32-ILP32Q-NEXT:    lw a1, 0(a0)
; RV32-ILP32Q-NEXT:    lw a2, 4(a0)
; RV32-ILP32Q-NEXT:    lw a3, 8(a0)
; RV32-ILP32Q-NEXT:    lw a4, 12(a0)
; RV32-ILP32Q-NEXT:    lw s0, 40(sp)
; RV32-ILP32Q-NEXT:    addi a0, sp, 8
; RV32-ILP32Q-NEXT:    sw a1, 8(sp)
; RV32-ILP32Q-NEXT:    sw a2, 12(sp)
; RV32-ILP32Q-NEXT:    sw a3, 16(sp)
; RV32-ILP32Q-NEXT:    sw a4, 20(sp)
; RV32-ILP32Q-NEXT:    call __fixtfsi
; RV32-ILP32Q-NEXT:    add a0, s0, a0
; RV32-ILP32Q-NEXT:    lw ra, 28(sp) # 4-byte Folded Reload
; RV32-ILP32Q-NEXT:    lw s0, 24(sp) # 4-byte Folded Reload
; RV32-ILP32Q-NEXT:    addi sp, sp, 32
; RV32-ILP32Q-NEXT:    ret
  %g_trunc = trunc i64 %g to i32
  %m_fptosi = fptosi fp128 %m to i32
  %1 = add i32 %g_trunc, %m_fptosi
  ret i32 %1
}

define i32 @caller_fp128_on_stack_exhausted_gprs_fprs() nounwind {
; RV32-ILP32Q-LABEL: caller_fp128_on_stack_exhausted_gprs_fprs:
; RV32-ILP32Q:       # %bb.0:
; RV32-ILP32Q-NEXT:    addi sp, sp, -208
; RV32-ILP32Q-NEXT:    sw ra, 204(sp) # 4-byte Folded Spill
; RV32-ILP32Q-NEXT:    addi a0, sp, 48
; RV32-ILP32Q-NEXT:    addi a3, sp, 64
; RV32-ILP32Q-NEXT:    addi a5, sp, 80
; RV32-ILP32Q-NEXT:    addi a7, sp, 96
; RV32-ILP32Q-NEXT:    addi t0, sp, 112
; RV32-ILP32Q-NEXT:    addi t1, sp, 128
; RV32-ILP32Q-NEXT:    li t2, 7
; RV32-ILP32Q-NEXT:    addi t3, sp, 144
; RV32-ILP32Q-NEXT:    lui t4, 262186
; RV32-ILP32Q-NEXT:    lui t5, 262184
; RV32-ILP32Q-NEXT:    lui a2, 262182
; RV32-ILP32Q-NEXT:    lui a1, 262180
; RV32-ILP32Q-NEXT:    lui a4, 262178
; RV32-ILP32Q-NEXT:    sw a0, 36(sp)
; RV32-ILP32Q-NEXT:    lui a6, 262176
; RV32-ILP32Q-NEXT:    sw t0, 20(sp)
; RV32-ILP32Q-NEXT:    sw a7, 24(sp)
; RV32-ILP32Q-NEXT:    sw a5, 28(sp)
; RV32-ILP32Q-NEXT:    sw a3, 32(sp)
; RV32-ILP32Q-NEXT:    lui a7, 262168
; RV32-ILP32Q-NEXT:    sw t3, 0(sp)
; RV32-ILP32Q-NEXT:    sw t2, 8(sp)
; RV32-ILP32Q-NEXT:    sw zero, 12(sp)
; RV32-ILP32Q-NEXT:    sw t1, 16(sp)
; RV32-ILP32Q-NEXT:    lui t0, 262160
; RV32-ILP32Q-NEXT:    sw zero, 48(sp)
; RV32-ILP32Q-NEXT:    sw zero, 52(sp)
; RV32-ILP32Q-NEXT:    sw zero, 56(sp)
; RV32-ILP32Q-NEXT:    sw t4, 60(sp)
; RV32-ILP32Q-NEXT:    lui t1, 262144
; RV32-ILP32Q-NEXT:    sw zero, 64(sp)
; RV32-ILP32Q-NEXT:    sw zero, 68(sp)
; RV32-ILP32Q-NEXT:    sw zero, 72(sp)
; RV32-ILP32Q-NEXT:    sw t5, 76(sp)
; RV32-ILP32Q-NEXT:    li a0, 1
; RV32-ILP32Q-NEXT:    sw zero, 80(sp)
; RV32-ILP32Q-NEXT:    sw zero, 84(sp)
; RV32-ILP32Q-NEXT:    sw zero, 88(sp)
; RV32-ILP32Q-NEXT:    sw a2, 92(sp)
; RV32-ILP32Q-NEXT:    addi a2, sp, 176
; RV32-ILP32Q-NEXT:    sw zero, 96(sp)
; RV32-ILP32Q-NEXT:    sw zero, 100(sp)
; RV32-ILP32Q-NEXT:    sw zero, 104(sp)
; RV32-ILP32Q-NEXT:    sw a1, 108(sp)
; RV32-ILP32Q-NEXT:    li a3, 3
; RV32-ILP32Q-NEXT:    sw zero, 112(sp)
; RV32-ILP32Q-NEXT:    sw zero, 116(sp)
; RV32-ILP32Q-NEXT:    sw zero, 120(sp)
; RV32-ILP32Q-NEXT:    sw a4, 124(sp)
; RV32-ILP32Q-NEXT:    addi a5, sp, 160
; RV32-ILP32Q-NEXT:    sw zero, 128(sp)
; RV32-ILP32Q-NEXT:    sw zero, 132(sp)
; RV32-ILP32Q-NEXT:    sw zero, 136(sp)
; RV32-ILP32Q-NEXT:    sw a6, 140(sp)
; RV32-ILP32Q-NEXT:    li a6, 5
; RV32-ILP32Q-NEXT:    sw zero, 144(sp)
; RV32-ILP32Q-NEXT:    sw zero, 148(sp)
; RV32-ILP32Q-NEXT:    sw zero, 152(sp)
; RV32-ILP32Q-NEXT:    sw a7, 156(sp)
; RV32-ILP32Q-NEXT:    sw zero, 160(sp)
; RV32-ILP32Q-NEXT:    sw zero, 164(sp)
; RV32-ILP32Q-NEXT:    sw zero, 168(sp)
; RV32-ILP32Q-NEXT:    sw t0, 172(sp)
; RV32-ILP32Q-NEXT:    sw zero, 176(sp)
; RV32-ILP32Q-NEXT:    sw zero, 180(sp)
; RV32-ILP32Q-NEXT:    sw zero, 184(sp)
; RV32-ILP32Q-NEXT:    sw t1, 188(sp)
; RV32-ILP32Q-NEXT:    li a1, 0
; RV32-ILP32Q-NEXT:    li a4, 0
; RV32-ILP32Q-NEXT:    li a7, 0
; RV32-ILP32Q-NEXT:    call callee_fp128_on_stack_exhausted_gprs_fprs
; RV32-ILP32Q-NEXT:    lw ra, 204(sp) # 4-byte Folded Reload
; RV32-ILP32Q-NEXT:    addi sp, sp, 208
; RV32-ILP32Q-NEXT:    ret
  %2 = fpext double 2.0 to fp128
  %4 = fpext double 4.0 to fp128
  %6 = fpext double 6.0 to fp128
  %8 = fpext double 8.0 to fp128
  %9 = fpext double 9.0 to fp128
  %10 = fpext double 10.0 to fp128
  %11 = fpext double 11.0 to fp128
  %12 = fpext double 12.0 to fp128
  %13 = fpext double 13.0 to fp128
  %14 = call i32 @callee_fp128_on_stack_exhausted_gprs_fprs(
      i64 1, fp128 %2, i64 3, fp128 %4, i64 5, fp128 %6, i64 7, fp128 %8,
      fp128 %9, fp128 %10, fp128 %11, fp128 %12, fp128 %13)
  ret i32 %14
}

define fp128 @callee_fp128_ret() nounwind {
; RV32-ILP32Q-LABEL: callee_fp128_ret:
; RV32-ILP32Q:       # %bb.0:
; RV32-ILP32Q-NEXT:    lui a1, 262128
; RV32-ILP32Q-NEXT:    sw zero, 0(a0)
; RV32-ILP32Q-NEXT:    sw zero, 4(a0)
; RV32-ILP32Q-NEXT:    sw zero, 8(a0)
; RV32-ILP32Q-NEXT:    sw a1, 12(a0)
; RV32-ILP32Q-NEXT:    ret
  %1 = fpext double 1.0 to fp128
  ret fp128 %1
}

define i32 @caller_fp128_ret() nounwind {
; RV32-ILP32Q-LABEL: caller_fp128_ret:
; RV32-ILP32Q:       # %bb.0:
; RV32-ILP32Q-NEXT:    addi sp, sp, -32
; RV32-ILP32Q-NEXT:    sw ra, 28(sp) # 4-byte Folded Spill
; RV32-ILP32Q-NEXT:    mv a0, sp
; RV32-ILP32Q-NEXT:    call callee_fp128_ret
; RV32-ILP32Q-NEXT:    lw a0, 0(sp)
; RV32-ILP32Q-NEXT:    lw ra, 28(sp) # 4-byte Folded Reload
; RV32-ILP32Q-NEXT:    addi sp, sp, 32
; RV32-ILP32Q-NEXT:    ret
  %1 = call fp128 @callee_fp128_ret()
  %2 = bitcast fp128 %1 to i128
  %3 = trunc i128 %2 to i32
  ret i32 %3
}
