; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv32 -mattr=+q -target-abi ilp32q \
; RUN:    -global-isel -stop-after=irtranslator -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefixes=RV32-ILP32Q %s

; This file contains tests that will have differing output for the ilp32/ilp32f
; and ilp32d ABIs.

define i32 @callee_fp128_in_fpr(i32 %a, fp128 %b) nounwind {
  %b_fptosi = fptosi fp128 %b to i32
  %1 = add i32 %a, %b_fptosi
  ret i32 %1
}

define i32 @caller_fp128_in_fpr() nounwind {
  %1 = fpext double 2.0 to fp128
  %2 = call i32 @callee_fp128_in_fpr(i32 1, fp128 %1)
  ret i32 %2
}

; Must keep define on a single line due to an update_llc_test_checks.py limitation
define i32 @callee_fp128_in_fpr_exhausted_gprs(i64 %a, i64 %b, i64 %c, i64 %d, i32 %e, fp128 %f) nounwind {
  %f_fptosi = fptosi fp128 %f to i32
  %1 = add i32 %e, %f_fptosi
  ret i32 %1
}

define i32 @caller_fp128_in_fpr_exhausted_gprs() nounwind {
  %1 = fpext double 6.0 to fp128
  %2 = call i32 @callee_fp128_in_fpr_exhausted_gprs(
      i64 1, i64 2, i64 3, i64 4, i32 5, fp128 %1)
  ret i32 %2
}

; Must keep define on a single line due to an update_llc_test_checks.py limitation
define i32 @callee_fp128_in_gpr_exhausted_fprs(fp128 %a, fp128 %b, fp128 %c, fp128 %d, fp128 %e, fp128 %f, fp128 %g, fp128 %h, fp128 %i) nounwind {
  %h_fptosi = fptosi fp128 %h to i32
  %i_fptosi = fptosi fp128 %i to i32
  %1 = add i32 %h_fptosi, %i_fptosi
  ret i32 %1
}

define i32 @caller_fp128_in_gpr_exhausted_fprs() nounwind {
  %1 = fpext double 1.0 to fp128
  %2 = fpext double 2.0 to fp128
  %3 = fpext double 3.0 to fp128
  %4 = fpext double 4.0 to fp128
  %5 = fpext double 5.0 to fp128
  %6 = fpext double 6.0 to fp128
  %7 = fpext double 7.0 to fp128
  %8 = fpext double 8.0 to fp128
  %9 = fpext double 9.0 to fp128
  %10 = call i32 @callee_fp128_in_gpr_exhausted_fprs(
      fp128 %1, fp128 %2, fp128 %3, fp128 %4, fp128 %5, fp128 %6,
      fp128 %7, fp128 %8, fp128 %9)
  ret i32 %10
}

; Must keep define on a single line due to an update_llc_test_checks.py limitation
define i32 @callee_fp128_in_gpr_and_stack_almost_exhausted_gprs_fprs(i64 %a, fp128 %b, i64 %c, fp128 %d, i64 %e, fp128 %f, i32 %g, fp128 %h, fp128 %i, fp128 %j, fp128 %k, fp128 %l, fp128 %m) nounwind {
  %m_fptosi = fptosi fp128 %m to i32
  %1 = add i32 %g, %m_fptosi
  ret i32 %1
}

define i32 @caller_fp128_in_gpr_and_stack_almost_exhausted_gprs_fprs() nounwind {
  %2 = fpext double 2.0 to fp128
  %4 = fpext double 4.0 to fp128
  %6 = fpext double 6.0 to fp128
  %8 = fpext double 8.0 to fp128
  %9 = fpext double 9.0 to fp128
  %10 = fpext double 10.0 to fp128
  %11 = fpext double 11.0 to fp128
  %12 = fpext double 12.0 to fp128
  %13 = fpext double 13.0 to fp128
  %14 = call i32 @callee_fp128_in_gpr_and_stack_almost_exhausted_gprs_fprs(
      i64 1, fp128 %2, i64 3, fp128 %4, i64 5, fp128 %6, i32 7, fp128 %8,
      fp128 %9, fp128 %10, fp128 %11, fp128 %12, fp128 %13)
  ret i32 %14
}


; Must keep define on a single line due to an update_llc_test_checks.py limitation
define i32 @callee_fp128_on_stack_exhausted_gprs_fprs(i64 %a, fp128 %b, i64 %c, fp128 %d, i64 %e, fp128 %f, i64 %g, fp128 %h, fp128 %i, fp128 %j, fp128 %k, fp128 %l, fp128 %m) nounwind {
  %g_trunc = trunc i64 %g to i32
  %m_fptosi = fptosi fp128 %m to i32
  %1 = add i32 %g_trunc, %m_fptosi
  ret i32 %1
}

define i32 @caller_fp128_on_stack_exhausted_gprs_fprs() nounwind {
  %2 = fpext double 2.0 to fp128
  %4 = fpext double 4.0 to fp128
  %6 = fpext double 6.0 to fp128
  %8 = fpext double 8.0 to fp128
  %9 = fpext double 9.0 to fp128
  %10 = fpext double 10.0 to fp128
  %11 = fpext double 11.0 to fp128
  %12 = fpext double 12.0 to fp128
  %13 = fpext double 13.0 to fp128
  %14 = call i32 @callee_fp128_on_stack_exhausted_gprs_fprs(
      i64 1, fp128 %2, i64 3, fp128 %4, i64 5, fp128 %6, i64 7, fp128 %8,
      fp128 %9, fp128 %10, fp128 %11, fp128 %12, fp128 %13)
  ret i32 %14
}

define fp128 @callee_fp128_ret() nounwind {
  %1 = fpext double 1.0 to fp128
  ret fp128 %1
}

define i32 @caller_fp128_ret() nounwind {
  %1 = call fp128 @callee_fp128_ret()
  %2 = bitcast fp128 %1 to i128
  %3 = trunc i128 %2 to i32
  ret i32 %3
}
